### ISSUE TITLE
Restructure Filter Components for Reusability Across All Data Types 

### ISSUE THREAD

**Issue by JorjaComer** [US-EPA-CAMD/PI-1#1435]
### Definition of Ready
- [x] Does this meet the INVEST criteria?
- [x] Does this have a clearly defined user?
- [x] Does this have an estimate?
- [x] Does this have acceptance criteria?
- [x] Does this have sufficient context (wireframes, business rules, etc.)?
- [x] Is this traceable to a feature, epic, or PI?

## User Story 
As CAMPD user I want to be able to view the filter criteria for facility, state, program, unit type, fuel type, and control technologies for Emissions, Allowance, and Compliance so that I can get data that I need. 

## Acceptance Criteria 
Given that a user has selected a data type and a data sub type 
When the filter criteria page is displayed 
Then the filters facility, state, program, unit type, fuel type, and control technologies are displayed, have data, and are interactive 

Given that a user has applied filter criteria
When the criteria is applied
Then the system displays a filter tag

Given that a user has applied filter criteria 
When the criteria is cleared
Then the system clears the criteria from the filter

## Context
No data is returned in preview. 
Data is selectable and can be applied 
Filter tags are displayed in accordance with requirements 

For reference: 
Facility: #890 , #1402 
State : #891
Program:  #1227
Unit type : #1407 
Fuel type: #894 

## Testing
Test Case: [TC184](https://cvpcorp.testquality.com/project/11428/plan/20058/test/283783)
Tester: @JanellC 

### Definition of Done
- [x] Have all Acceptance Criteria been agreed to and validated by the scrum team?
- [ ] Has the code been unit tested and peer reviewed?
- [x] Have the functional tests been executed?
- [ ] Have all defects been reviewed and dispositioned, resolved, or deferred?
- [ ] Has the user story been accepted by the Product Owner?
- [ ] Is the user story ready to be deployed to the test/staging environments?

**Comment by JanellC** [comment]
@addisgmichael 
From [12:04 PM] Lageman, Travis
    
Hey Addis Gebremichael (Guest) I would've left this comment in the ticket but can't click it because the ready to test column is collapsed. Anyways, the filters are looking good but wanted to clarify a couple of errors I'm seeing:
1) Program - Allowance Holdings is correct in that it should only contain the active allowance programs. However, Allowance Transactions and Account Information need to ensure that all allowance Programs (both active/retired) are available in the filter.
2) Program - In Compliance  Allowance based , the program filter has some programs that are not allowance based. The list of available programs should be both active and retired, but only allowance based.
3) Daily Emissions - I noticed that the time period filter has the operating hours only checkbox, which should be excluded in this particular filter. 

Let me know if I can clarify further, but this information should be in the features for the respective data subtypes. Thanks and keep up the good work!

**Comment by JanellC** [comment]
TC184 failed @tlageman-epa . Logged the bugs listed below to track the changes. 

1. Bug: Update Allowance programs #1481

2. Bug: Update Allowance Program filter to include OTC and NBP #1482

3. Bug: Update Compliance (Allowance based) program filter #1483
