### ISSUE TITLE
Mid Fi Bulk Data Download (need by 7/26)

### ISSUE THREAD

**Issue by JorjaComer** [US-EPA-CAMD/PI-1#1688]
Create mid fi designs for bulk data download. Schedule to be reviewed with EPA on 7/26. 

### Assets

- [Responsive Sizes](https://www.figma.com/proto/RV8X37LPqM6RVztvNpjns0/CAMPD-Product-Designs?node-id=232%3A18&scaling=scale-down-width&page-id=232%3A17&starting-point-node-id=232%3A18)
- [FTP Access Help modal](https://www.figma.com/proto/RV8X37LPqM6RVztvNpjns0/CAMPD-Product-Designs?node-id=232%3A94&scaling=scale-down-width&page-id=232%3A17&starting-point-node-id=232%3A94)

**Comment by cvp-alexrobinson** [comment]
@tlageman-epa —

Hello,

As promised, [here is a link to the Bulk Data Files design](https://www.figma.com/proto/RV8X37LPqM6RVztvNpjns0/CAMPD-Product-Designs?node-id=232%3A18&scaling=scale-down-width&page-id=232%3A17&starting-point-node-id=232%3A18). You'll also notice that I moved the FTP help text out of the page, and into a modal that's accessible by tapping "Need help accessing the FTP site?" That flow can be found [here](https://www.figma.com/proto/RV8X37LPqM6RVztvNpjns0/CAMPD-Product-Designs?node-id=232%3A94&scaling=scale-down-width&page-id=232%3A17&starting-point-node-id=232%3A94). 

Please let me know if you have any questions or comments.

CC @JanellC @JorjaComer @MoAdeyoju

**Comment by tlageman-epa** [comment]
Alex, this is looking good. A few initial comments:


  1.  Remove the first sentence under each section (not sure where those came from) as they seem a bit redundant with the grouping titles
  2.  Also remove the ; after each bullet
  3.  Remove the "And" between the last 2 bullets in all four sections
  4.  Edit the sentence in the FTP access help modal "Option 2: Recent changes to Chrome and Edge require a settings change in order to be able to download files in these browsers."
  5.  Could you provide a couple options on how to declutter the bullets that have and update frequency in parentheses? (e.g., updated annually) It seems cluttery and if possible I'm not sure if its best to use a symbol to indicate updated annually and one updated quarterly or if there should be a simple table with the datasets and update frequency? Looking for your expertise here.

Thanks!
Travis

**Comment by tlageman-epa** [comment]
On further thought, let's go ahead and remove the "by Program" lines in allowance and compliance, "by Year,..." Lines in emissions and raw emissions, and remove the "active & retired programs" and in allowance/compliance sections. Just to declutter further.

Travis

**Comment by cvp-alexrobinson** [comment]
@tlageman-epa — Thanks for the quick feedback! [I created a Word document](https://usepa.sharepoint.com/:w:/r/sites/CAMDCVPTeam/_layouts/15/Doc.aspx?sourcedoc=%7B11DD8C0E-3CCA-4502-B370-64FD61DEF748%7D&file=2-Bulk%20Data%20Files.docx&action=default&mobileredirect=true&cid=a78867c1-3869-4d58-8293-30000b713c42) that we can use as the "source of truth" for this page's content. 

I've addressed 1-4 (in the Word doc) from your first comment, but I would like your guidance on your other comments. Please feel free to directly edit that Word document and comment here when it's ready to go. 

If you can get this revised first thing Monday morning, I can update the design file for the team review during the CAMPD Product Design session at 1pm.

Best,
Alex

**Comment by tlageman-epa** [comment]
Morning Alex, edits have been made to the word doc. Used track changes so they were clear. Thanks!

Travis

**Comment by cvp-alexrobinson** [comment]
Thanks, @tlageman-epa. These designs have been updated.

**Comment by tlageman-epa** [comment]
Hey Alex, apologies, I missed the last section. Everything else looks good. Could you make this last change. Thanks!


Raw Emissions (XML)

*       Emissions Submittals by Year, Quarter & Facility (updated quarterly)

*       Monitoring Plan Submittals by Facility

*       QA data by Year, Quarter & Facility (updated quarterly)
