### ISSUE TITLE
Mid Fi MP Validation and Validation Outcome Page Design (need by 8/23)

### ISSUE THREAD

**Issue by JorjaComer** [US-EPA-CAMD/PI-1#1691]
Message for validation in progress
Validation outcome page

**Comment by cvp-alexrobinson** [comment]
@chrisgitsit —

[Here's a link to the prototype](https://xd.adobe.com/view/dafd3617-1b98-4133-923c-00fc316755fb-8fae/) for the MP validation flow in ECMPS. Some things to note:

- This is based on [this flow from ZenHub](https://app.zenhub.com/workspaces/datateers-scrum-board-5f36cc8dfed6db0022b0f4db/issues/us-epa-camd/easey-ui/170)
- There are a few things animating so it might lag the first time around. So click on "Evaluate," run through the whole animation, then view the report. After you run through it once, it should run smoother (it has to cache).
- Visual feedback:
    - The "Evaluate" becomes both the progress meter, and the success message.
    - Once the evaluation has started, "Check back in" is disabled, the config tab icon changes from a pencil to a lock, a cancel link appears next to the evaluation progress indicator, and the eval status meta info goes away.
    - Once evaluation is complete, the config is unlocked, "Check back in" is enabled again, a direct link to the newest report appears next to the eval status meta message, and a "New" tag appears next to "Reports."
    - "Reports" and "Report" modals are intentionally left blank. Exiting these modals will take you back to frame one of the flow.
    - Hoping that all these visuals will convey what's happening, give them and exit, and give them in-context feedback on where to find the results of their eval.

Let me know if you have any issues with the prototype, or if you have any questions

**Comment by cvp-alexrobinson** [comment]
For the future... Set up a visual pattern for those evaluations that might take a longer time, or still give you that evaluation progress on current evaluations if you navigate away.

**Comment by cvp-alexrobinson** [comment]
@AllisonFrancis @vishnunavuluri — Looping you into a possible design solution for those evaluations that might take a longer time, and/or a solution that will still give you that evaluation progress on current evaluations if you navigate away. Since this is done in React, I was thinking we could use stacking snack bars. In [this notistack demo](https://material-ui.com/components/snackbars/#complementary-projects), click the first example, then the second. So if someone navigates away, the progress snack would come up, and others would stack as they evaluate other MPs or emissions files. Then the progress snacks would turn into success snacks when they're done and offer them a link to the report.

No action necessary, just looping you into an idea I had so it doesn't get lost.
