### ISSUE TITLE
SPIKE: Handle switching between different tabs and different Views

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#1962]
Consider user switching between different views (Global and Workspace) with a configuration open.

Expected Behavior: When a user has a tab open in the Workspace and navigates to the Global-View, then the tab open in the Workspace is not available in the Global view and vice versa. Tabs need to be closed by the user in any of the views.

Needed to close bug #1956

**Comment by tdavydets** [comment]
In order to make it happen, we would need to:
*  identify in source code all dependencies and values to which they need to be set in order to open/re-open any tabs potentially opened by user after the screen has loaded.

* A redux data structure would have to be created (pending detailed analysis) to store identified dependencies and their values

* Actions / reducer cases would have to be set up to properly handle updates to Redux

* Lastly, we'd have to verify that updates and their effects get properly propagated to all relevant places within the application, and their propagation has desired effect on the user interface
