### ISSUE TITLE
Track CAMPD traffic via google analytics 

### ISSUE THREAD

**Issue by JanellC** [US-EPA-CAMD/PI-1#2075]
## Context 

During backlog refinement on 9/22 the Datateers PO mentioned that he would like to implement google analytics for CAMPD so that EPA has data on how users are navigating the site. The EPA will look into how google analytics is currently used for AMPD and provide guidance to CVP. 

Google analytics should only be activated for public pages in production using an environment variable switch

**Implementation instructions from EPA Resource:**
Use the code in the stand alone template
Use the index.html file
Search the code for Google Tag Manager
Note: Part of the code is in the section and part is in the Instructions from Google Analytics

Here’s the general code from the EPA
(function (w, d, s, l, i) { 
               w[l] = w[l] || []; w[l].push({ 
                              "gtm.start": new Date().getTime(), event: "gtm.js" 
               }); var f = d.getElementsByTagName(s)[0], 
                              j = d.createElement(s), dl = l != "dataLayer" ? "&l=" + l : ""; j.async = true; j.src = 
                                             "//www.googletagmanager.com/gtm.js?id=" + i + dl; f.parentNode.insertBefore(j, f); 
})(window, document, "script", "dataLayer", "CONTAINER_ID");

However, not sure this can just be dropped into a React application since React is a SPA and there are Open Source packages we need to look into using.
 
For the production environment any public pages need to use GTM-L8ZB as the CONTAINER_ID.
For all other environments (Dev, Test, Stage) the code should be disabled.

We will need a container id that we can use in develop to test an ensure that this is all working along with access to the Google Dashboard to confirm that we are seeing metrics.

**Comment by MaeganWood64** [comment]
Discussion from TT Planning 10/14, that each team will implement the google tag on their own pages. Should only be activated for public pages in production using an environment variable switch 

PO's would like to implement google analytics to ECMPS and CAMPD in order to track a variety of metrics native to the google analytics suite.

Implementation instructions from EPA Resource:

Use the code in the stand alone template
Use the index.html file
Search the code for Google Tag Manager
Note: Part of the code is in the section and part is in the

Instructions from Google Analytics

**Comment by JanellC** [comment]
Target for the end of PI-6

**Comment by JanellC** [comment]
The tech team is researching how to implement the REACT package for google analytics. Once the research is complete we can tackle this ticket
