### ISSUE TITLE
Provide format for CDD helper text (need by 11/3)

### ISSUE THREAD

**Issue by JorjaComer** [US-EPA-CAMD/PI-1#2167]
Need format of text, margins, padding, location, responsiveness etc. 

Helper Text:

Build a query by choosing a data type and subtype. Click Apply.
Refine query by using available filters. Selection must be made for required filter.
Click Preview Data to view data selection.
Hover over the “?” marks to reveal helpful tool tips.

![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/0f2692ab-fa9d-4890-90e1-05ba0a5672cb)

**Comment by AllisonFrancis** [comment]
@JanellC I did respond in teams to Travis. But i think we'll need clarification about the filters panel and how that pops out to be used while the helper text sits behind it on the white screen per my wireframes.

Also, i have updated the spacing of the helper text to be consistent with the preview data frames per Junie 24pix. 
[CAMPD CDD Helper Text](https://www.figma.com/file/RV8X37LPqM6RVztvNpjns0/CAMPD-Product-Designs?node-id=1422%3A4343)

Per Anthony's point yesterday on the call, please let me know what the final replacement text should be instead of "Hover over the ?..."  Thanks

**Comment by AllisonFrancis** [comment]
I have updated the pages so that the helper text appears on the filters panel per our call on Monday 11/15. 
@JanellC we still need the updated text to resolve the "Hover" issue. 
Links in Teams but here is the link for dev
[CAMPD CDD Helper Text Updates (dev) 11/16](https://www.figma.com/file/RV8X37LPqM6RVztvNpjns0/CAMPD-Product-Designs?node-id=1422%3A4343)
