### ISSUE TITLE
Timeout Errors during Unit testing

### ISSUE THREAD

**Issue by srinivasaregeti** [US-EPA-CAMD/PI-1#223]
Found some information on Stackoverflow:

https://stackoverflow.com/questions/49603939/async-callback-was-not-invoked-within-the-5000ms-timeout-specified-by-jest-setti

**Comment by jwhitehead77** [comment]
The timeout error mentioned above is occurring because the unit test is actually calling the FACT API which at times is taking longer than the 5 sec default jest timeout setting. This is evident in the fact that the pipeline can be rerun and the test will sometimes pass and sometimes fail.

The reason the test eventually started to fail consistently was due to data changes within the FACT API data which caused the actual response length to no longer match the expected response length.

Unit tests should never call out to external dependencies (i.e. call api's or databases) as we are not testing the API or database calls. Their purpose is to test the features, functions, and components within the application that perform operations on the data returned by those external dependencies.

@addisgmichael is going to address this unit test in his next push
