### ISSUE TITLE
Spike: Research querying up until the current date 

### ISSUE THREAD

**Issue by JanellC** [US-EPA-CAMD/PI-1#2272]
## Context 

The allowance transactions filter logic endpoint does not query up until the current date. It was discovered that the system allows a user to query up until the last day the endpoint was built. This issue will need to be addressed for all endpoints that query up until the current date. The team needs to research how to handle querying up until the current date 

The issue is applicable to:
hourly emissions
daily emissions
allowance transactions
allowance transactions filter logic endpoint

**Comment by junie-stigdon** [comment]
Problem: The DTOs and validators are initialized at compile time. So using 'new Date()' in the DTO or validation pipe would only ever return the date and time of when it compiled.

Solution: Added a computed property getCurrentDate to the DTO. It updates an instance of the object so it will get the current date when called, rather than just being instantiated once at compile time.
