### ISSUE TITLE
Check Out Issues/Observations

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#2339]
Fix these requirements for checking out a configuration on these pages:

**Select Configurations:**
- When a user checks out a configuration, the "Open & Checkout" links should change to "Open" for any other configuration to prevent multiple checkouts by a single user
- When a user checks out a configuration, the "Open & Checkout" links for configuration in the same facility should change to "Open" for all users.

**Monitor Plan**
- When a user checks out a configuration, the "Check out" button should be hidden for all configurations in a facility with a checked-out configuration.
- When a user checks out a configuation, the "Check out" button should be hidden to a user who already has a checked-out configuration.  They should only be able to see the "Check in" button on their checked-out configuration.

**Comment by dionolympiaCVP** [comment]
During backlog refinement with Chris, he stated that the configuration tab does not need the Lock icon added.

The issue is that when a facility is locked (from someone checking-out a configuration), other users can still check out other configurations in the same facility.  Instead, we need to disable check-out functionality for ALL configurations of a locked facility.

**Comment by mosesdeeCVP** [comment]
The Check Out button is no longer visible in any other configuration once the user has already checked out a configuration prior.

![2339 Check Out Issues-Observations.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/fad4b19b-5966-45e6-938e-8727d2b2db02)

**Comment by mosesdeeCVP** [comment]
Test Passed
