### ISSUE TITLE
Code Clean Up-PI 6

### ISSUE THREAD

**Issue by JanellC** [US-EPA-CAMD/PI-1#2375]
## Context 
- Only for UI Work 
- [ ] Increase code coverage to at least 70%
- [ ] Clean Up Unnecessary Commented Code 
- [ ] Remove Unused Import Statements
- [ ] Remove unused functions from the redux action for filter criteria 
- [ ] Remove unused components 
- [ ] Clean up console warning messages (ex. warning messages on the custom data download)

**Comment by AbuFofanah** [comment]
Modified multiselect combo-box component to break iteration when the component is no longer mounted. Modified tooltip component to clear timeout and not display tooltip information when component is no longer mounted. Deleted the selectable card component and its styling since they are no longer used. Added tests to the manage data download component and the filter criteria menu component  to improve test coverage. Modified filter criteria test to reflect changes to the code. Changed default state for datatype and data subtype to empty strings instead of null since the datatype for those states are always strings.
