### ISSUE TITLE
Spike: Monitoring Plan - Import Merging Logic

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#2481]
Notes from Dwayne:

The MP import merging logic is in the ECMPS SQL Server ECMPS_WS database. The main stored procedure is the ECMPS_WS.Import.MonitoringPlan. It calls a set of child SP in the Import schema in the ECMPS_WS database that being with "MP_". Those procedures all seem to try to match the imported records with an existing record and update the matching record if it exists, but otherwise insert a new record.  

Someone would need to look at each of these SP to determine how the matching is done for each type of record.

**Comment by sanleyCVP** [comment]
Already fleshed out the validation and merging logic into Workspace. We are still looking in the Check Engine validation and the ECMPS_WS.Import.MonitoringPlan procedure

**Comment by sanleyCVP** [comment]
Need to confirm the following before closing:
1. Should this process be enabled for retired MPs?
2. Should we allow the import process be triggered at the Mp selection screen?
3. Is the MP import restricted to one MP per file? or Should the process support import of multiple files at a time? 
4.  Confirm that Import checks 5,6 and 9 will compare against the Workspace schema

**Comment by sanleyCVP** [comment]
![image.png](https://images.zenhubusercontent.com/6143891f8447a5585788734a/2e2c799d-04ab-4063-8578-3ea61cbe87a9)

**Comment by sanleyCVP** [comment]
![image.png](https://images.zenhubusercontent.com/6143891f8447a5585788734a/8a8dd527-8d3e-4f0a-8711-f8c6deace27a)

**Comment by sanleyCVP** [comment]
Moved all the comments from this ticket to #2340 where the overall process of validation is reflected. Pending definition of the merge logic for each MP module/section

**Comment by sanleyCVP** [comment]
The sequence of updates in current process:
**monitor_plan** - no updates are made to the monitoring plan table. Insert if none exist for the fac_id and begin_rpt_period_id (or end_rpt_period_id is no record found for begin period). The rpt_period_ids are obtained camdecmpswks.vw_reporting_period view. We need to also consider the unit/stack/mon_location information to determine the existence of a Monitor Plan. The Begin date for a monitoring plan, for matching to the reporting period, is equal to the earliest BEGIN_DATE in any MONITOR_METHOD record for any location in the MP (default in case of none is 1/1/2000) 

IF MP with UnitStackConfiguration
**stack_pipe** - If no stack pipe id exists for the fac_id and stack_name, insert new stack pipe, else update [ACTIVE_DATE], [RETIRE_DATE], [USERID], [UPDATE_DATE] when active and retired date are different

**unit_stack_configuration** - If no unit_stack_config record exists for the fac_id, stack pipe id, and unit_id insert a new configuration, else update [BEGIN_DATE], [END_DATE], [USERID], [UPDATE_DATE]
END UnitStackConfiguration

**unit** - Import doesn't create new units, so if unit doesn't exist error out. For Units associated to the fac_id only update if NON_LOAD_BASED_IND has changed (update user id and Update date fields as well)

**unit capacity** - lookup unit capacity record by unit_id and begin date (or end date if no match found for begin date). If no unit_cap_id found, insert new record, else update [BEGIN_DATE], [END_DATE], [MAX_HI_CAPACITY], [USERID], [UPDATE_DATE] where either begin date, end date, or max_hi_capacity values have changed

**unit control** - lookup ctl_id by unit_id, ce_param, control_cd, install_date (or retired date if no match found for install date). If no ctl_id found insert new record, else update [ORIG_IND], [SEAS_IND], [OPT_DATE], [INSTALL_DATE=, [RETIRE_DATE], [USERID], [UPDATE_DATE] where of those values has changed

**unit fuel** - Lookup uf_id by unit_id, fuel_cd, begin_date (or end date if no match found for begin date). If no uf_id found insert new record, else update DEM_GCV, DEM_SO2,  BEGIN_DATE, END_DATE, INDICATOR_CD, OZONE_SEAS_IND, USERID, UPDATE_DATE where any of those values has changed

**Monitor Location/Monitor Plan Location** - 
Obtain mon_loc_id to lookup values in all MP sections and merge or insert new records
1. ORISCode from file --> fac_id from camd.plant
2a. For MonitoringLocationData.UnitID elements:
fac_id from **1** --> unit_id from camd.unit --> mon_loc_id from camdecmpswks.monitor_location
2b. For MonitoringLocationData.StackPipeID elements:
fac_id from **1** --> stack_pipe_id from camdecmpswks.stack_pipe --> mon_loc_id from camdecmpswks.monitor_location
if mon_loc_id is null from initial lookup above insert new monitor_Location record. If no record exists for the mon_loc_id and mon_plan_id in the monitor_plan_location table, insert a new record (mon_plan_id is passed as a parameter)

**Monitor Location Attributes** -  Lookup mon_loc_attr_id by mon_loc_id, begin_date (or end date if no match found for begin date). If no mon_loc_attr_id exists insert a new record, else update [GRD_ELEVATION], [DUCT_IND], [BYPASS_IND], [CROSS_AREA_FLOW], [CROSS_AREA_EXIT], [BEGIN_DATE], [END_DATE], [STACK_HEIGHT], [SHAPE_CD], [MATERIAL_CD], [USERID], [Update_DATE] where any of the values have changed

**Monitor Method** - lookup mon_method_id by MON_LOC_ID, PARAMETER_CD, BEGIN_date/hour (or end date/hour if no match for begin date). If no mon_method_id exists insert a new record, else update SUB_DATA_CD, BYPASS_APPROACH_CD, METHOD_CD, BEGIN_DATE, BEGIN_HOUR, END_DATE, END_HOUR, USERID, Update_DATE where any of the values have changed

**Monitor MATS Method** - lookup mon_method_id by MON_LOC_ID, PARAMETER_CD, BEGIN_date/hour (or end date/hour if no match for begin date/hour). If no mats_method_id exists insert a new record, else update MATS_METHOD_PARAMETER_CD, MATS_METHOD_CD, BEGIN_DATE, BEGIN_HOUR, END_DATE, END_HOUR, 		USERID, Update_DATE where any of the values have changed

**Component (See Note 4)** - lookup component_id by mon_loc_id and component_identifier. If no component_id exists insert a new record, else update MODEL_VERSION, SERIAL_NUMBER, HG_CONVERTER_IND, MANUFACTURER, COMPONENT_TYPE_CD, ACQ_CD, BASIS_CD, USERID, UPDATE_DATE where any of the values have changed

**Analyzer Range** - lookup analyzer_range_id by component_id and begin date/hour (or end date/hour if no match for begin date exists).  If no analyzer_range_id  exists insert a new record, else update ANALYZER_RANGE_CD, DUAL_RANGE_IND, BEGIN_DATE, BEGIN_HOUR, END_DATE, END_HOUR, USERID, ADD_DATE where any of the values have changed

**Monitor System (See Note 4)** - lookup mon_sys_id by mon_loc_id and system_identifier. If no mon_sys_id exists insert a new record, else update SYS_TYPE_CD, SYS_DESIGNATION_CD, FUEL_CD, BEGIN_DATE, BEGIN_HOUR, END_DATE, END_HOUR, USERID, Update_DATE where any of the values have changed

**Monitor System Component** - lookup mon_sys_comp_id by MON_SYS_ID, COMPONENT_ID, BEGIN_DATE, and BEGIN_HOUR. If no mon_sys_comp_id exists insert a new record, else update END_DATE, END_HOUR, USERID, Update_DATE where any of the values have changed

**Monitor System Fuel Flow** -  lookup sys_fuel_id by mon_sys_id, begin data/hour (or end date/hour if no match for begin date exists).  If no sys_fuel_id exists insert a new record, else update MAX_RATE, SYS_FUEL_UOM_CD, MAX_RATE_SOURCE_CD, BEGIN_DATE, BEGIN_HOUR, END_DATE, END_HOUR, USERID, Update_DATE where any of the values have changed

**Monitor Formula (See Note 4)** - lookup mon_form_id by mon_loc_id and formula_identifier. If no mon_form_id exists insert a new record, else update PARAMETER_CD, EQUATION_CD, FORMULA_EQUATION, 					 BEGIN_DATE, BEGIN_HOUR, END_DATE, END_HOUR, USERID, Update_DATE where any of the values have changed

**Monitor Span** - lookup span_id by MON_LOC_ID, COMPONENT_TYPE_CD, SPAN_SCALE_CD, begin_date/hour (or end date/hour if no match for begin date exists). If no span_id exists insert a new record, else update SPAN_METHOD_CD, MPC_VALUE, MEC_VALUE, MPF_VALUE, SPAN_VALUE, FULL_SCALE_RANGE, SPAN_UOM_CD, MAX_LOW_RANGE, DEFAULT_HIGH_RANGE, FLOW_SPAN_VALUE, FLOW_FULL_SCALE_RANGE, BEGIN_DATE, BEGIN_HOUR, END_DATE, END_HOUR, USERID, Update_DATE where any of the values have changed

**Monitor Default** - lookup mondef_id by MON_LOC_ID, PARAMETER_CD, DEFAULT_PURPOSE_CD, FUEL_CD, OPERATING_CONDITION_CD, begin_date/hour (or end date/hour if no match for begin date exists). If no mondef_id exists insert a new record, else update DEFAULT_VALUE, DEFAULT_UOM_CD, DEFAULT_SOURCE_CD, BEGIN_DATE, 						BEGIN_HOUR, END_DATE, END_HOUR, USERID, Update_DATE where any of the values have changed

**Rectangular Duct Waf** - lookup rect_duct_waf_data_id by mon_loc_id and begin_date/hour (or end date/hour if no match for begin date exists). If no rect_duct_waf_data_id exists insert a new record, else update WAF_DETERMINED_DATE, WAF_EFFECTIVE_DATE, WAF_EFFECTIVE_HOUR, WAF_METHOD_CD, WAF_VALUE, NUM_TEST_RUNS, NUM_TRAVERSE_POINTS_WAF, NUM_TEST_PORTS, NUM_TRAVERSE_POINTS_REF, DUCT_WIDTH, DUCT_DEPTH, END_DATE, END_HOUR, USERID, Update_DATE where any of the values have changed

**Monitor Load** - lookup load_id by MON_LOC_ID, begin_date/hour (or end date/hour if no match for begin date exists). If no load_id exists insert a new record, else update LOAD_ANALYSIS_DATE, MAX_LOAD_VALUE, SECOND_NORMAL_IND, UP_OP_BOUNDARY, LOW_OP_BOUNDARY, NORMAL_LEVEL_CD, SECOND_LEVEL_CD, MAX_LOAD_UOM_CD, BEGIN_DATE, BEGIN_HOUR, END_DATE, END_HOUR, USERID, Update_DATE where any of the values have changed

**Monitor Qualification** - lookup mon_qual_id by MON_LOC_ID, QUAL_TYPE_CD, begin_date (end date if no match for begin date exists).  If no mon_qual_id exists insert a new record, else update QUAL_TYPE_CD, BEGIN_DATE, END_DATE, USERID, Update_DATE where any of the values have changed

**Monitor Qualification PCT** - lookup mon_pct_id by mon_qual_id and qual_year. If no mon_pct_id exists create a new record, else update [QUAL_YEAR], [YR1_QUAL_DATA_TYPE_CD], [YR1_QUAL_DATA_YEAR], [YR1_PCT_VALUE],  [YR2_QUAL_DATA_TYPE_CD], [YR2_QUAL_DATA_YEAR], [YR2_PCT_VALUE], [YR3_QUAL_DATA_TYPE_CD], [YR3_QUAL_DATA_YEAR], [YR3_PCT_VALUE], [AVG_PCT_VALUE], [USERID], [UPDATE_DATE] where any of the values have changed

**Monitor Qualification LEE** - lookup mon_qual_lee_id by mon_qual_id and qual_test_date. If no mon_qual_lee_id exists create a new record, else update QUAL_TEST_DATE, PARAMETER_CD, QUAL_LEE_TEST_TYPE_CD, POTENTIAL_ANNUAL_EMISSIONS, APPLICABLE_EMISSION_STANDARD, EMISSION_STANDARD_UOM, EMISSION_STANDARD_PCT, [USERID], [UPDATE_DATE] where any of the values have changed

**Monitor Qualification LME** - lookup mon_lme_id by mon_qual_id and qual_data_year. If no mon_lme_id exists create a new record, else update [QUAL_DATA_YEAR], [SO2_TONS], [NOX_TONS], [OP_HOURS], {USERID], [UPDATE_DATE]  where any of the values have changed

**Monitor Plan Comment** - lookup mon_plan_comment_id by mon_plan_id, mon_plan_comment and begin_date. If no mon_plan_comment_id exists create a new record, else update [END_DATE], [USERID] when the end date has changed

**Additional Notes:** 
1. If a Monitoring Plan is pending submission Import cannot happen (block button in UI?)
2. At the end of Import, if successful, update MP eval Status to "Needs Evaluation" (Current process calls Update_ECMPS_Status SP)
3. In the current system, the Monitor Plan ID is obtained by using the import session, since the import process is managed by the check-engine. This is not the case moving forward, so we will have to obtain the monitor plan id and monitor location ids using the stack_pipe, unit and facility information provided in the file (details are above)
4. For Component, Monitor System, Monitor Formula if the ID's are not obtained as described above, they current process results for looking up in the Used_Identifier table by Code, mon_loc_id and identifier=id of element being looked up
5. All of our APIs take mon_loc_id as a parameter to create/update data in the DB

**Comment by sanleyCVP** [comment]
Merge Logic:
**Monitor Plan & Monitor Locations** 

1. Obtain the fac_id with the ORISCode from file --> fac_id from camd.plant
2. Obtain all mon_plan_ids (camdecmpswks.monitor_plan) by fac_id from 1
3. For each location entry in the JSON file, obtain the associated mon_loc_id from the DB as follows
 3a. For Location.UnitID elements: fac_id from 1 --> unit_id from camd.unit --> mon_loc_id from camdecmpswks.monitor_location
  3b. For Location.StackPipeID elements: fac_id from 1 --> stack_pipe_id from camdecmpswks.stack_pipe --> mon_loc_id from camdecmpswks.monitor_location
**_The import process will trigger an error if there is not a monitor location associated to the facility for the given Stack/Unit_**
4. Obtain the mon_plan id for each mon_loc_id obtained in 3 from camdecmpswks.monitor_plan_location
5. All mon_plan_id from 4 must be the same and must match an active version of the mon_plan_ids identified in 2
**_Import process will trigger an error if there is a mismatch of mon_plan_ids in 5, or if the mon_plan_id being updated is inactive_**

**Monitor Comment**
Once we have a valid Monitor Plan ID, we insert the MP Comment records from the file

Then update the following sections:
**_Stack_** 
Update the information of the stack if a match is found, if not trigger an error

**_Unit Stack Configuration_**
- Update the configuration information if a match is found, if not trigger an error

**_Unit_**
- Update the unit information when a location.unitId for the fac_id record is found. Also update the Unit Capacity, Unit Control and Unit Fuel records by matching to the unit's DB Id

** Monitor Location Details **
With the mon_loc_id create/update the location details for:
1. Monitor Location Attributes
2. Monitor Method and Monitor MATS Method 
3. Component and Analyzer Range
4. Monitor System, Monitor System Component, and Monitor System Fuel Flow
5. Monitor Formula
6. Monitor Span
7. Monitor Default
8. Rectangular Duct Waf
9. Monitor Load
10. Monitor Qualification, Monitor Qualification PCT, Monitor Qualification LEE, and Monitor Qualification LME

**Comment by sanleyCVP** [comment]
Confirm with Chris if the import process is limited to update existing MPs
