### ISSUE TITLE
CAMPD subheader and utility nav responsiveness - 508 Issue 

### ISSUE THREAD

**Issue by JanellC** [US-EPA-CAMD/PI-1#2504]
## Context 

Testing complete for 1651, multiple issues found:

There's an extra tab stop after the hamburger menu icon and before the preview data tooltip, not exactly sure what it is but should be removed.

When I expand the hamburger menu, focus should be put on the collapse button and vice versa.

The hamburger menu has no state information. (Aria expanded). Code similar to the Menu button.

When expanded, only the Home link is keyboard accessible, all the expandable/collapsible elements can only be used with a mouse (data, resources, etc.)

The expandable/collapsible elements don't have state information. Code similar to how they are on desktop.

**Comment by aprematta** [comment]
Everything is good except for the last item: The expandable/collapsible elements don't have state information. Code similar to how they are on desktop.. Screen readers do not pick up the state. Think the problem here is that the aria expanded is on the list item instead of the anchor. li class="usa-sidenav__item" aria-expanded="false"
a class="usa-current" tabindex="0">DATA<svg class="MuiSvgIcon-root float-right" focusable="false" viewBox="0 0 24 24" aria-hidden="true"><path d="M7.41 8.59L12 13.17l4.59-4.58L18 10l-6 6-6-6 1.41-1.41z"></path></svg></a

**Comment by aprematta** [comment]
No remaining issues, closing ticket
