### ISSUE TITLE
Monitoring Plan Check Engine Testing

### ISSUE THREAD

**Issue by MaeganWood64** [US-EPA-CAMD/PI-1#2622]
- Complete testing of the MP check engine 

- [ ] Using existing MP Check Engine API endpoint to validate any inconclusive MP results

**Comment by sanleyCVP** [comment]
Test results were provided by ERG during the meeting of 3/7/2022. 

**Failed SPAN-20-B Case** (ERG to fix #2766)
- The SPAN_INDICATOR for HF in COMPONENT_TYPE_CODE in the ECMPS Client database is null, but it is 1 in the EASEY-IN database (and the CAMDBS Host database).
- SPAN-1-1, SPAN-21-C, SPAN-50-A and SPAN-52-A fire.
- I assume this discrepancy between the ECMPS Client and CAMDBS Host occurred during MATS development and that the ECMPS Client is correct.
- ERG needs to conclusively determine the change that should occur.
**COMPON-13-C fires for component type “OP” with sample acquisition “ISC” and a null basis.** (#2797)
- The ECMPS DB "Component Type and Basis to Sample Acquisition Method" crosscheck has a row for "OP" and "ISC" with a null basis.
- The EASEY-IN DB crosscheck has "OP-hide" component types instead of "OP" and two of the three rows, including "ISC", have a "W" basis instead of null.  As a result, a match is not found in the crosscheck and COMPON-13-C is produced.
- The EASEY-IN crosscheck has "H2O-hide" instead of "H2O" for 8 rows with 5 having a basis instead of null.
- In the EASEY-IN crosscheck, "TANK" and "TRAP" each have a row with the “-hide" postfix.
- Excel Workbook Retest Status: “Passed w/ COMPON-13-C Issue”.
- CVP needs to investigate the reason/cause of the “-hide” rows in the “Component Type and Basis to Sample Acquisition Method” crosscheck.
**CONTROL-2-B Fires** (#2759)
-The EASEY-IN DB CONTROL_CODE 'SB' control code on the host has a null CONTROL_EQUIP_PARAM_CD, but the ECMPS Client DB has four 'SB" entries, one each for 'HCL', 'HF', 'HG' and 'SO2'.
-CONTROL-2-C fires because an 'SO2'/'SB' CONTROL_CODE row does not exist.
-The EASEY-IN DB CONTROL_CODE table matches the CAMDBS Host DB.
-The differences between the ECMPS Client DB and the CAMDBS Host DB make sense because the host CONTROL_CODE is just a lookup table, but the client CONTROL_CODE also contains crosscheck information.
-ERG and CVP will need to discuss how to handle this issue.
CVP may need to consider changing the primary key to CONTROL_CD and CONTROL_EQUIP_PARAM_CD, and updating the data to match the ECMPS Client data.
**METHOD-14-F Fires** (to be addressed with check engine updates #2201)
-This result was eliminated in the 2021 Q3 ECMPS release in August 2021.
-Excel Workbook Retest Status: “Passed w/ METHOD-14-F Issue”.
-ERG needs to list and provide METHOD-14 and any other checks that may have changed.

The tickets flagged as blockers were created to address some of the findings before retest can occur
