### ISSUE TITLE
SPIKE: Custom Data Download Accepting dates without data 

### ISSUE THREAD

**Issue by MaeganWood64** [US-EPA-CAMD/PI-1#2645]
- Custom Data Download is accepting dates with no data. Spike needed to research the root cause of this issue

## Steps to Reproduce
1. Navigate to the custom data download
2. Select hourly emissions 
3. Apply time period criteria for 12/31/2021 
4. Select preview data 

The system accepts the time period even though there is no data associated with the date. 

### Actual Results

The system accepts the time period 12/31/2021  even though there is no data available for that date. This happening for years after 2010. When data is not available for a time period the system should display an alert and prompt the user to enter in a new time period. This is applicable to all emissions sub types. 

Note: This bug should not be an issue in prod. Would only occur in lower environments where all the data is not available. Once in prod, we will reverify and retest this ticket with all data in the environment.

**Comment by junie-stigdon** [comment]
The issue with the dates is happening because there is data in AnnualUnitData that doesn't exist in HourUnitData. For example, the HourUnitData table currently has no data in 2008, but AnnualUnitData does. And because the filter logic endpoint uses AnnualUnitData for all emissions subtypes, we run into this issue.

This problem occurs even in the years that HourUnitData does have data for. So say on 01/01/2020, there were no hourly emissions data whatsoever. There's still hourly data in the year 2020, just not on that specific day. But since the filter logic endpoint only cares about the year, not individual day, it will return all applicable data for 2020 despite there being no hourly data.

One way of solving this would be to make a filter logic endpoint for each of the emissions subtypes, but that seems like overkill for an issue that ideally shouldn't happen in production (not even sure if it's feasible for hourly data b/c of its toll in performance). But relying solely on AnnualUnitData may lead to edge cases. (We also currently have no way of accounting for operatingHoursOnly)

**Comment by junie-stigdon** [comment]
Development for ticket #2556 no longer needed. Will retest once in prod.
