### ISSUE TITLE
Add/ remove data elements on the cdd - 508 issue 

### ISSUE THREAD

**Issue by JanellC** [US-EPA-CAMD/PI-1#3486]
## Context 

Testing complete, keyboard functionality has been added but there are additional 508 issues:

2.	I can tab to the arrows used to sort the columns, but when I hit enter focus is lost, it should stay on the arrow that I activated
3.	The sorting arrows have aria-hidden=true which hides them to a screen reader
4.	The sorting arrows lack a role of button
5.	The sorting arrows lack a programatic name, suggest adding an aria label that says to sort by ascending/descending and the column name
6.	When activating the additional options (with the 3 dots), the overlay with the 4 options display, but I can tab past them to other fields. The focus should be trapped until I make a selection or I hit the escape key
7.	When I do make a selection, focus is lost, it should be placed back on the 3 dots
8.	The 3 dots have aria-hidden=true which hides them to a screen reader
9.	The 3 dots lack a role of button
10.	The 3 dots lack a programatic name, suggest adding an aria label that says additional options and the column name
11.	After making the customize column selection, The focus should be trapped until I make a selection or I hit the escape key
14.	The column title text field lacks a programatic label. Suggest turning the 'Find Column' div into a label tag and associating it to the input.
15.	Focus is lost when I hit the Apply button.

**Comment by aprematta** [comment]
Much improved, 3 issues remain:

The sorting arrows are still not properly announced to a screen reader. It might be because aria-labelledby was used instead of an aria-label. I don't see 'sort by descending' as an id anywhere
aria-labelledby="sort by descending"

The 3 dots are still not properly announced to a screen reader. It might be because aria-labelledby was used instead of an aria-label. I don't see 'sadditional options - Facility Name' as an id anywhere
aria-labelledby="additional options - Facility Name"

The find column label has the for attribute of "find column" but the input has an id of "textField", these need to match

**Comment by aprematta** [comment]
Remaining issues have been fixed. Note.... for some reason the buttons are not picked up in ANDI... however they are announced with a screen reader.
