### ISSUE TITLE
Update V-PAT from 508 Testing

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#3613]
508 testing of ECMPS to be done at the end of I & P sprint for PI 8

**Comment by aprematta** [comment]
Here are the results of the testing so tickets can be created, VPAT to follow:
1. When the menu is expanded, the button next to the search field no longer says search so there is no visible label
2. When zoomed into 200%, the hamburger menu cannot be expanded

https://easey-tst.app.cloud.gov/ecmps/export
3. When in a configurations tab, the test summary section should be in a live region
4. Aria labels for individual checkboxes are non specific in the test summary table. For example aria-label="select-row-TWCORNEL5-ED43ABD50CC846EE8263A66EBE2A8C0F" Need to tie to a unique characteristic of each row
5. The test summary data table has no programmatic name
6. Test summary data cells have a role of gridcell instead of cell
7.  On the select configuration tab, 'Select Configurations' is a div..... it should be at a heading 3

https://easey-tst.app.cloud.gov/ecmps/monitoring-plans
8. The following tables have a role of gridcell instead of Cell: Defaults, Formulas, Loads, Unit Fuels, Spans
9. These tables also have no aria-sort value
10. The Unit Fuels data table has no programatic name

https://easey-tst.app.cloud.gov/ecmps/qa_certifications_test_summary_data
11.  On the select configuration tab, 'Select Configurations' is a div..... it should be at a heading 3
12. On the configurations tab, the test summary data table has an incorrect aria label aria-label="DataTable Aria Label Missing"
13. There are multiple view links.... these need additional programatic description so they are unique
14. When closing the test summary modal, focus does not return to the appropriate view button
15. Focus is lost when expanding/contracting a row, focus should stay on the +/- element
16. The focus state of the +/- relies on the changing of the title attribute, aria expanded=true/false is more reliable
17. On the import historical test data modal, the preview summary table data cells have gridcell instead of cell
18. On the import historical test data modal, Aria labels for individual checkboxes are non specific

https://easey-tst.app.cloud.gov/ecmps/monitoring-plans - When Logged in
19. Selecting a Parameter moves the focus to the close button, it should remain on the parameter field
20. Error messages are not compliant, they close the window and all values are lost.
21. Need a method on every modal to indicate which fields are required as well as any special formatting requirements that might exist. This needs to be both visual and programmatic.

**Comment by aprematta** [comment]
VPAT completed and uploaded to https://teams.microsoft.com/_#/files/TheEmissioners?threadId=19%3A56d336e3060849efa0557d379b78d9ca%40thread.skype&ctx=channel&context=VPATs&rootfolder=%252Fsites%252FCAMDCVPTeam%252FShared%2520Documents%252FTheEmissioners%252F7-508%2520Testing%252FVPATs
