### ISSUE TITLE
MP, QA: Move errors/validations to inside the Modal

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#3672]
When a user is working on MP data and QA Test Data and a screen validation is displayed, the modal needs to be closed to review the error or in some cases is closed automatically 

User loses the data since it is not saved at this point

Resolution: Display the validations inside the create/view/edit modals

**Comment by JanellC** [comment]
Bug not resolved 

Use Cases: 

**MP**
For the Monitoring Plan, when Adding or Editing data, leave the End hour or Start Hour empty after entering the Date. Then you should see the validations since we need to enter both the Date and the Time together in order to be able to save

![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/23864262-823c-436c-be9f-4c84d94f1e3f)

System displays the validation on the screen and not in the modal 


**QA** - works as expected 
![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/4efd0e53-dd7b-4d2a-8bb1-4e4b2e347659)

When saving a QA record, if the user omits a test type code the system does not display an error message at all. @vishnunavuluri will track this issue seperatly

**Comment by JanellC** [comment]
Bug resolved 

**MP**
![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/a0553e85-60dc-4788-86d3-06a76879204e)

![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/266b63b0-5520-4934-9715-8ff8f6eb2286)


**QA**

![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/ffffa48d-389f-4d89-b343-2c24a00e2530)
