### ISSUE TITLE
Test Only: Revert to Official Record bug 

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#3826]
**Issue:**
Revert to Official Record functionality is not working

Steps to Reproduce:
- Login to ECMPS using your credentials
- Select and open a Configuration in the Monitoring Plans workspace
- Make updates as needed in any of the available sections
- Once you save the updates, click Revert to Official Record
- Verify if the updates have been reverted

**Comment by JanellC** [comment]
Based on discussion during DSU on 7/21, the revert to official record button is working however it is taking some time to process in the background. Instead of working on this bug, the team should implement a spinner for the button so that a user is aware that the action is processing. @vishnunavuluri

**Comment by mosesdeeCVP** [comment]
Bug is fixed
