### ISSUE TITLE
CAMPD 508 Issues - Program Increment 10

### ISSUE THREAD

**Issue by MaeganWood64** [US-EPA-CAMD/PI-1#3958]

**Comment by aprematta** [comment]
Testing complete for 3555, found the following 508 issues:
1. On the first slide (Allowance Story Map) the background that displays with the U.S. map has low contrast where the city names are against a dark blue background or the state borders. Since this is a screenshot of the actual system it should be ok but it is possible that the EPA 508 team could flag.
2. When tabbing through the slideshow portion, there are tab stops where the user does not have any visual focus. I believe these are the links available when slides are inactive. For example, if the first slide is active, I think the links from slides 2,3,4 are getting focus. They should only get focus if the slide is active.
3. There are three links all named 'Provide Feedback'. They should have additional context with either hidden text or an aria label such as 'Provide feedback for Allowance Storymap'
4. There are 2 links named 'Github Repository' They should have additional context with either hidden text or an aria label such as 'Github Repository for Facility Map'
5. Below the slideshow and paragraph, Allowance Storymap, Facility Map and Program Insights need to be at a Heading level 2
6. Andi is complaining about the carousel slide buttons because they are not tabable. You can access with the left/right arrows so keyboard wise it should be ok..... but again EPA 508 may flag to either make them tabable..... or add instructions saying that that the user needs to use the arrow keys to navigate.

**Comment by aprematta** [comment]
No issues found with 4288

**Comment by aprematta** [comment]
No issues found for 4171. In Jaws the pipe is announced as 'vertical bar' but there's nothing we can do to change it to something else like 'pipe' (in regard to the instructions). Actual use of the query is compliant and users still have the option of selecting one by one which was already deemed compliant
