### ISSUE TITLE
Spike: Research Data Caveat Implementation

### ISSUE THREAD

**Issue by MaeganWood64** [US-EPA-CAMD/PI-1#3972]
In order to complete the work outlined in #3461, additional research is needed to see on how to implement a data caveat
**Requirements**

- [ ]  look into whether the caveat is on the facility or unit level

- [ ] Look into implementation on the backend

- [ ] Look into implementation on the front end

**Notes** 

- After further review, the current data caveats are being pulled from a materialized view and snapshot tables. Further research is required to see which tables are needed to be brought over/ how they are involved

**Comment by tlageman-epa** [comment]
Relevant info from ERG:

Yes, you are correct-- AMPD checks to see if any of the orispl codes in the query data match either the ORISPL_CODE (the code uses FAC_ID, not ORISPL_CODE) or OLD_ORISPL_CODE fields in the MV_DATA_LOG_ALIAS table and then pulls the necessary associated caveat information.

Regards,
Ann

On 2022-04-27 09:08:57, TLageman wrote:

> Good Morning,

> Previously, Ann shared with me that the data caveats information is 
> stored in the MV_DATA_LOG_ALIAS table (CAMDPUB). I want to confirm how 
> the query tool determines which records to display from this table 
> based on the user’s query. Based on what I see, does AMPD check to see 
> if any of the orispl codes in the query data match either the 
> ORISPL_CODE or OLD_ORISPL_CODE fields in the MV_DATA_LOG_ALIAS table 
> and then pull the necessary associated caveat information? Or is it 
> more complicated than that?

See data caveats sheet (not including instructions) currently in [tutorials ](https://campd.epa.gov/help-support/tutorials)section of campd for example of desired file output.

**Comment by jwhitehead77** [comment]
This is probably around a 21 story point feature all together...

The following tables would be required...
- camd.plant_alias
- camd.unit_alias
- camd.unit_logical_move
- camd.unit_physical_move

High level Details...
- These tables will need to be added to the camdbsp nightly CDC job so that cloud.gov stays in sync with oracle.
- Add views necessary for Informatica to handle the sync similar to other camd tables being synced (ex. plant).
- Create views on the cloud.gov side that presents data in similar fashion as the UNIT_HISTORY_SS and MV_DATA_LOG_ALIAS materialized views in oracle.
- Modify all paginated api endpoints used to preview data on custom data download page to check if caveats exists and provide a flag, either in header or response, as to whether caveats exist or not
- Create api endpoint that would take a list of units/facilities and return the caveat data based on that list.
- Add a mechanism to download the caveats data to the campd ui on the custom data download page.
