### ISSUE TITLE
Emissions Module 508 Testing

### ISSUE THREAD

**Issue by acollad1** [US-EPA-CAMD/PI-1#4071]
## Epic Benefit
Emissions Module Issues that require 508 testing 

## Context

508 Compliance Checklist 
![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/8c22190f-28ca-4e46-9763-dd6c4d5e184d)

**Comment by aprematta** [comment]
3959 testing complete, no issues found

**Comment by aprematta** [comment]
3960, 3961, 3962 testing complete, 'Select Configurations' heading should be at an H3, currently it is a div. Occurs on all 3 pages. No other issues found

**Comment by aprematta** [comment]
Testing complete for 4106, couple issues:
1. When I select a configuration (barry 4) with the keyboard, focus jumps to the quarter dropdown.... it should stay at Barry 4. 
2. Similarly, when I hit the Select Configurations button with the keyboard, it should stay on that button
3. After I make selections with the keyboard for year or quarter, focus is placed at the top of the page instead of staying where it is
4. Similarly, if I remover a quarter or year the focus is placed at the top of the page
5. 'When I expand the Daily Calibration view, focus is placed at the top of the page
6. It looks like the full heading is not captured in a heading tag. For example, Grayson Power Plant is in an H3 tag, but the number 4 is in a paragraph tag

**Comment by aprematta** [comment]
No issues found with 4376

**Comment by aprematta** [comment]
1 issue found for 4420:
Visually, the Download to CSV button comes after the expand/collapse button. However, when tabbing through the page the Download to CSV button receives focus first. Adjust the positioning in the DOM to move the button after the heading:
![image](https://user-images.githubusercontent.com/67421847/201788268-d90c83e8-bc37-44fe-aa9b-505eb90c2375.png)

**Comment by aprematta** [comment]
1 issue found for 4417:
When making a selection via keyboard.... for example 2009 Q2..... the selection is made but focus is lost and put at the top of the page. It should remain on the item selected. The same issue occurs when removing an item.

**Comment by aprematta** [comment]
1 issue found for 4294:
When closing the module, focus does not return to the Import Data Button
