### ISSUE TITLE
MP/ QA 508 Testing- PI 11 

### ISSUE THREAD

**Issue by JanellC** [US-EPA-CAMD/PI-1#4150]
## Context 

508 issues fo MP/QA 

508 Compliance Checklist 
![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/8c22190f-28ca-4e46-9763-dd6c4d5e184d)

**Comment by aprematta** [comment]
3 issues found for 4081:
1. The revert to official record button has an incorrect tab order because the tabindex is set to 1 instead of 0
![image](https://user-images.githubusercontent.com/67421847/201791561-0208ac05-a45b-4a7f-91be-0dacbc6e8d1a.png)

2. The configuration is not part of the heading:
![image](https://user-images.githubusercontent.com/67421847/201792054-9c0acc4f-f238-4342-8ac4-fd11023d3301.png)

3. Heading levels for tables should be adjusted to H4 so it is hierarchy is under the Location/Configuration of H3
![image](https://user-images.githubusercontent.com/67421847/201792424-45a9ad1e-4082-42d3-8f33-552c1286ab9e.png)
