### ISSUE TITLE
508 Testing Only: QA Test Type - Linearity Summary

### ISSUE THREAD

**Issue by JanellC** [US-EPA-CAMD/PI-1#4291]
## Context 

Complete 508 testing on linearity test type. The scope of this  ticket is for Global and Workspace view and the following levels: 
Test Summary, Linearity Test, Linearity Injection and Protocol Gas Data

Note: Configuration Glen Lyn 51 (Oris Code 3776) has test data 

**Global View (non-logged in):** 
- Need to test the view functionility for the following Linerairty summary levels : Test Summary, Linearity Test, Linearity Injection and Protocol Gas Data 

**Work spacee: Logged in View:** 

-  Need to test the view, add, edit, and remove for the following Linerairty summary levels : Test Summary, Linearity Test, Linearity Injection and Protocol Gas Data 

Note: in order to see the  view, add, edit, and remove you must check out the configuration

**Comment by aprematta** [comment]
Testing complete, most of the issues from ticket #3613 apply. Here are the specific results:
1. There are multiple view/evaluate/edit/remove links.... these need additional programmatic description so they are unique
2. When closing modals, focus does not return to the appropriate view, edit, remove buttons
3. Focus is lost when expanding/contracting a row, focus should stay on the +/- element
4. The focus state of the +/- relies on the changing of the title attribute, aria expanded=true/false is more reliable
5. All tables reviewed lack a programmatic name, most have invalid aria labels aria-label="DataTable Aria Label Missing"
6.  All tables reviewed have the data cells with a role of gridcell instead of cell which breaks the association to the table headers
7. When adding..... fields that are required are not marked as required
8. On the import historical test data modal, Aria labels for individual checkboxes are non specific
