### ISSUE TITLE
508 Testing Only: Rata

### ISSUE THREAD

**Issue by JanellC** [US-EPA-CAMD/PI-1#4385]
## Context 

Complete 508 testing on Rata Test type: 
The scope of this  ticket is for Global and Workspace view and all of the Rata levels and As apart of the scope of this ticket test Refactor Open Configurations/tabs Across Modules (Global-view & Workspace) #3887 as well

Note: Configuration Glen Lyn 51 (Oris Code 3776) has test data 

**Global View (non-logged in):** 
- Need to test the view functionility for all Rata levels 

**Work spacee: Logged in View:** 

-  Need to test the view, add, edit, and remove for all rata levels 

Note: in order to see the  view, add, edit, and remove you must check out the configuration . Testing be conducted in dev 

https://ecmps-dev.app.cloud.gov/qa-test

**Comment by JanellC** [comment]
@aprematta This ticket is ready for testing

**Comment by aprematta** [comment]
This has the same issues as 4291

1There are multiple view/evaluate/edit/remove links.... these need additional programmatic description so they are unique*
2 When closing modals, focus does not return to the appropriate view, edit, remove buttons
3 Focus is lost when expanding/contracting a row, focus should stay on the +/- element
4 The focus state of the +/- relies on the changing of the title attribute, aria expanded=true/false is more reliable
5 All tables reviewed lack a programmatic name, most have invalid aria labels aria-label="DataTable Aria Label Missing"
6 All tables reviewed have the data cells with a role of gridcell instead of cell which breaks the association to the table headers
7 When adding..... fields that are required are not marked as required
8 On the import historical test data modal, Aria labels for individual checkboxes are non specific*

* - Most likely, when I was logged in there was no data, however there was data on the non logged in view
