### ISSUE TITLE
Modify Export API to Return an Empty Array 

### ISSUE THREAD

**Issue by acollad1** [US-EPA-CAMD/PI-1#4472]
As an ECMPS system, I need to make sure the export API is returning an empty array in order for the import functionality to work properly.

Given a test type doesn't have data
When it is exported
Then the export for that test type returns an empty array 

- [x] Cange this so that the export is returning an empty array because the import process expects those fields to never be null

- [ ] Remove the function written in the UI which was used to circumvent this requirement

**Comment by fanwari1** [comment]
The following URL can be used to test this ticket:
`/emissions-mgmt/emissions/export?monitorPlanId=MDC-9FF127451AE0415ABF9BBF6A0B036A1A&year=2021&quarter=1`

You can use a different year and quarter to do other tests. 

Also, postman should be used to make these requests since the data exported is fairly large and will crash swagger.
