### ISSUE TITLE
508 Issue: QA Test Data Section - Update Focus

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#4509]
Issue:
When closing the Add/Remove modal for Test Data/Test Summary Data section, focus does not return to the appropriate view. Update it as below:

**Add:** Save and Close - Focus goes to the Edit for the newly added record
         Cancel - Focus back to the Add
**Remove:** Confirm - Focus goes to Add
                Cancel - Focus retained on Remove

![image.png](https://images.zenhubusercontent.com/610014e44c513c0bad9f811c/c810fccc-4589-4e4b-8672-c8ddaf35db45)

**Comment by aprematta** [comment]
It looks like there might be an issue when the first record is added to a blank table. It's losing focus instead of going to the edit button. it's ok after the first record is added. Experienced in linearity summary, appendix E correlation, Calibration Injection. I still need to test the others but am having log in issues

**Comment by subrataroyCVP** [comment]
Issue resolved. Ready to Re-test.

**Comment by aprematta** [comment]
Retest complete, focus shift is now working when there is a blank table. No other issues found
