### ISSUE TITLE
Perform Emissions Overall Unit Test Audit 

### ISSUE THREAD

**Issue by acollad1** [US-EPA-CAMD/PI-1#4519]
As an ECMPS developer, I want to review all existing unit tests to ensure they are all good well-written tests that serve a purpose. 

- [x] Remove/Modify any unit tests that the audit has determined are "bad" tests

- [x] Comment in this ticket any files that have had unit tests removed as a result of this audit

- [x] Fix failing unit test (file names list below)

derivedhourlyvalueparamDTO
hourlygasflowmeterservice

**Comment by sdhawan16** [comment]
**Outcome of Audit:** 
- Unit tests were fixed for DerivedHourlyValueParamsDto and HourlyGasFlowMeterService
- All apportioned emissions controllers and services tests were modified to pass in mock data instead of empty objects

Additional Info for #4517 - 

Current Unit Test Coverage  is 76%

The following modules need additional tests to reach 80% coverage:
apportioned-emissions (top level module) - 58.69%
apportioned-emissions/mats/hourly - 73.61%
daily-emission - 55.55%
daily-emission-workspace - 53.12%
derived-hourly-value-functions - 30.43%
emissions - 78.3%
emissions-workspace - 72.01%
hourly-fuel-flow - 61.53%
hourly-fuel-flow-workspace - 67.85%
hourly-operating-functions - 30.43%
hourly-operating-workspace - 76.31%
monitor-system-workspace - 0%
nsps4t-summary - 59.09%
nsps4t-summary-workspace - 34.14%
sorbent-trap - 57.89%
sorbent-trap-workspace - 47.05%
summary-value-functions - 63.63%
