### ISSUE TITLE
Bulk Data Files File Description Incorrect 

### ISSUE THREAD

**Issue by MaeganWood64** [US-EPA-CAMD/PI-1#4564]
- Bulk Data Files File Descriptions are not displaying correctly. MATS is missing descriptions entirely, and Allowance Holdings Data is Appearing as ALlowance Transactions Data. 

**Notes**
- Fix is in feature branch "fix/descriptions-release" , will be merged in post 1.1 

**Testing**

- Verify All Descriptions match those outlined in the[ File Names and Descriptions Spreadsheets](https://usepa.sharepoint.com/:x:/r/sites/CAMDCVPTeam/_layouts/15/doc2.aspx?sourcedoc=%7B4B2DBBA7-2970-40F9-A7EA-0294354E2020%7D&file=File%20names%20and%20descriptions.xlsx&action=edit&mobileredirect=true&wdPreviousSession=3b32563e-4a60-4dbb-8b90-274135bc058e&wdOrigin=TEAMS-ELECTRON.teamsSdk.undefined)

**Comment by tlageman-epa** [comment]
@Kyle-Herceg  I noticed a few additional description errors that were not captured. Let me know if you have any questions or if these are not quick fixes:
- Under compliance data, the compiance-arpnox file description is incorrect. It says "Acid Rain Program Annual...." when it should say "Acid Rain NOx Program Annual..."
- For hourly, daily, and mats emissions state datasets, the description has the state abbreviation whereas it should have been the full state name so that the keyword search bar would actually work for those data files (see context for cvp column in linked spreadsheet). Not sure if that is an easy fix or not. Thx
