### ISSUE TITLE
SPIKE: Long Polling vs Server Sent Events vs WebSockets for MP Checkin/Checkout

### ISSUE THREAD

**Issue by MaeganWood64** [US-EPA-CAMD/PI-1#4640]
- Currently utilizing stadard polling. Will be switched to an actual endpoint to send a request to get that actual response and the UI would wait for a response. 
- Need to make sure that long polling is compatible with the environment and 3rd party (api.data.gov) requirements
- Could potentially be leveraged for submissions to obtain the status

**Comment by MaeganWood64** [comment]
- Not needed for March Beta

**Comment by jwhitehead77** [comment]
Long Polling is very resource intensive on the server due to each client having a long running request waiting for a response. Server Sent Events has connection limitations unless using http 2.0. The best option is a full duplex pub/sub message based approach that allows the server to broadcast to all clients anytime a checkin or checkout occurrs. Based on this websockets is the best approach.
