### ISSUE TITLE
Implement Deactivate Functionality in the Error Suppression Table

### ISSUE THREAD

**Issue by acollad1** [US-EPA-CAMD/PI-1#4686]
As an ECMPS user, I want to be able to deactivate data in the error suppression table so that it will no longer appear in active searches

Given a user has navigated to the error suppression table 
When  the user clicks on the deactivate check mark for a line item
Then the warning pop-out will appear

Given a deactivate warning pop-out appears
When the user confirms in the pop-out that they want to deactivate the data
Then the pop-out closes and the deactivate check box will be marked for the selected line item

Given a user has successfully deactivated a line item in the error suppression table
When the user views that line item
Then the deactivate check box will be disabled (greyed out)  and that set of data will no longer appear in the active search

https://projects.invisionapp.com/freehand/document/1dwq6maiy?zoomToItems=Y2xidmJqaWZrMDBhajNiNnh1bWdycXRtcw%3D%3D

**Comment by AmandaMNelson** [comment]
Note: The Invision board was updated such that there is a status column showing active vs. inactive status, a checkbox to select any line item, and a button above the table that deactivates any selected line items. After an active item is deactivated, it's status changes to inactive in the status column, and nothing is greyed out, since the select checkbox still needs to be available for cloning if necessary.
