### ISSUE TITLE
ECMPS 508 Testing/Scan - During 11.5 - I&P sprint 

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#4726]
## Context 

Complete 508 scan of ECMPS application. See comments below for 508 feedback

**Comment by aprematta** [comment]
Results when a user is NOT logged in:
https://ecmps-tst.app.cloud.gov/emissions
1. When the page first loads, focus is on select configurations, should really be at the top of the page (occurs on other pages as well)
2. There is no visible label for search on the Menu pop out, the default text does not count in 508. Easiest solution is to change the magnifying glass icon into a button that says 'Search'
3.  Change the generic link 'Here' in the what's new section to something more descriptive
4. What's new should be a heading (h3), currently it's a div.

https://ecmps-tst.app.cloud.gov/monitoring-plans
The following issues were flagged on the CAMPD 508 scan by EPA. All tables throughout the website should mirror the behavior of the table on https://campd.epa.gov/data/bulk-data-files 
1. Table headers do not have up/down arrow visible on focus only on mouseover
2. Focus box does not stay visible when sorting column headers
3. Don't put aria sort until it is sorted by ascending/descending (so remove aria sort=none, only set aria sort when the column is set to ascending or descending)
4. Give an aria label to the headers 'click to sort by <header name>
-----------------------------------------------------------------------------
Non table issues:
5. On glen lyn 51 - when I collapse then expand Supplemental Methods, focus goes to methods ^
6. API Communications error - I received a lot of these during testing, for this message the contrast is lower than 4.5:1, also
7. Api communication error is not in Aria live
8. There is an empty H4 on the page that should be removed
9. On the View printout report, headings like Facility Information should be at an H2
10. On View Comments window, bold heading should be at an H2....and the table needs either a caption or an aria label

https://ecmps-tst.app.cloud.gov/qa-test
1. When I select a configuration, focus shifts to first view button, it should stay put
2. When I expand, focus shifts to view button. Sometimes the one underneath, sometimes the previous view button
3. Aria Label for first level tables is "Datatable Aria label missing" instead of a unique label (observed on all test types)

https://ecmps-tst.app.cloud.gov/qa-cert-event
1. View aria label is 'not implemented yet'

https://ecmps-tst.app.cloud.gov/emissions
1. Bad request error message is not in an aria live and has low contrast
2. Close out  X for the message is also inaccessible (Aria hidden = true and no accessible name)
3. I was unable to find data to test

https://ecmps-tst.app.cloud.gov/export
1. I was unable to find data to test

**Comment by aprematta** [comment]
Result when a user is logged in:
General:
1. Just to reiterate, the data table issues from the previous comment apply to all tables throughout the entire application.
2. Error messaging when Adding/Editing is very inconsistent. There should be 1 method on all Add/Edit modals where:
A. The modal is not closed
B. All entered information is retained
C. The error is identified clearly in text to the user
D. The error message either receives focus or is in an aria live region
Monitoring plans entry is currently the most inaccessible because the window is closed and the error messages are hard to understand.
QA test data is a bit better but seems to rely on pop ups and only flags 1 error at a time
QA Cert data doesn't seem to have any error handling, if I add a new item and just click save and close, it kicks me out of the modal but the modal isn't closed
3. Error Prevention... Required fields need to be marked as such in the label. Formatting requirements should also be included if a special format is required for successful submission.

 By page:
https://ecmps-tst.app.cloud.gov/workspace/monitoring-plans
1. Revert to Official Record modal does not return focus to the button
2. Evaluation status and submission status are not in live region
3. View comments modal does not return focus to the button
4. Making a parameter select shifts focus to the close button instead of keeping focus where it is.

https://ecmps-tst.app.cloud.gov/workspace/qa-test and https://ecmps-tst.app.cloud.gov/workspace/qa-cert-event
1. Evaluate, Edit, remove links are not unique seems consistent with every test type group
2. When add buttons have focus, text color changes to black and the contrast is low

https://ecmps-tst.app.cloud.gov/workspace/emissions
1. Closing window from Revert to official record does not return focus to the button

https://ecmps-tst.app.cloud.gov/workspace/export
1. Test summary table and 'There are no records to display message' should be in an aria live region
2. Configuration is not in the H3 (for example, glen lyn is, but 51 is in its own div)

https://ecmps-tst.app.cloud.gov/workspace/evaluate & https://ecmps-tst.app.cloud.gov/workspace/submit
1. Data tables do not have accessible names
2. View buttons are not unique
3. checkboxes have no accessible names
4. expand/collapse elements are not keyboard accessible

https://ecmps-tst.app.cloud.gov/workspace/error-suppression
1. Modals do not return focus to original buttons
2. toggle calendar names are not unique
