### ISSUE TITLE
Bug: Add Export Button (Bottom of the screen)

### ISSUE THREAD

**Issue by vishnunavuluri** [US-EPA-CAMD/PI-1#5138]
The Export button at the bottom of the screen for both Global-view and Workspace has been removed. This needs to be added back as it is helpful when there is a lot of data on the screen and users have to scroll in order to review it

**Comment by subrataroyCVP** [comment]
Pull Request: https://github.com/US-EPA-CAMD/easey-ecmps-ui/pull/1048

**Comment by mosesdeeCVP** [comment]
Export Button on bottom of screen Global
![Export Button on bottom of screen Global.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/c26e593f-8952-4786-96b6-1c317802011a)

Export Button on bottom of screen Workspace
![Export Button on bottom of screen Workspace.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/07aaf919-5705-4a2e-8e1f-77e59bcee860)

**Comment by subrataroyCVP** [comment]
## @mosesdeeCVP Made some update. Export button will be only visible when QA-Cert checkbox is checked.

**Comment by mosesdeeCVP** [comment]
Second Export Button not visible as expected 
![Second Export Button not visible as expected .png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/460a11bd-c7b0-4aca-bfce-40d4c226034c)

Second Export Button is visible as expected since QA is selected
![Second Export Button is visible as expected since QA is selected.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/90e769d0-7112-414e-a313-41c520b839ac)

Second Export Button is visible and active since QA data is selected
![Second Export Button is visible and active since QA data is selected.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/d7964ac9-c716-4961-9c37-cac9e175158c)

**Comment by mosesdeeCVP** [comment]
Second Export Button not visible as expected 
![Second Export Button not visible as expected .png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/460a11bd-c7b0-4aca-bfce-40d4c226034c)

**Comment by mosesdeeCVP** [comment]
Second Export Button not visible as expected 
![Second Export Button not visible as expected .png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/460a11bd-c7b0-4aca-bfce-40d4c226034c)

**Comment by mosesdeeCVP** [comment]
Updates have been completed successfully.
