### ISSUE TITLE
Review and IDentify Columns for QA/Cert Maintenance Data Endpoints 

### ISSUE THREAD

**Issue by acollad1** [US-EPA-CAMD/PI-1#5265]
As an ECMPS user, I need to have the columns for the QA/Cert Maintenance Data endpoints identified so we know what needs to be returned and validated.

- [ ] Need to review the QA tables

**Comment by fanwari1** [comment]
[Qa-cert-maintenance-spike.zip](https://github.com/US-EPA-CAMD/easey-ui/files/11665864/Qa-cert-maintenance-spike.zip)

QA Cert Data Maintenance

* All data types will have a corresponding view from which we will pull data.
vw_qa_cert_event_maintenance
vw_qa_test_summary_maintenance
vw_qa_test_extens_exempt_maintenance
* The fields marked as (show) will be shown in the UI
* The type parameter in the UI will drive which end point is called

ENDPOINT: GET /camd-services/admin/qa-maintenance/test-summary

Parameters: 
orisCode (required) 
unitStack 

Response:
{
    "testSumId": string 
    "locationId": string 
    "unitStack": string (show)
    "systemIdentifier": string (show combined with component – SysId/CompId if both)
    "componentIdentifier": string (show combined with system – SysId/CompId if both)
    "testNumber": string (show)
    "gracePeriodIndicator": number 
    "testTypeCode": string (show)
    "testResultCode": string 
    "yearQuarter": string (show)
    "testDescription": string 
    "beginDateTime": string (show)
    "endDateTime": string (show)
    "testComment": string 
    "spanScaleCode": string 
    "submissionAvailabilityCode": string 
    "submissionAvailabilityDescription": string (show)
    "severityCode": string 
    "severityDescription": string (show)
}

Notes:
“Identifying Data” will be separated into two columns, Test Number and Test Type
There is a one to one relationship between test_summary record and qa_supp_data record
Might want to consider not showing facility in the table since it needs to be selected in the dropdown

Query:
CREATE OR REPLACE VIEW camdecmps.vw_qa_test_summary_maintenance
AS SELECT 
ts.test_sum_id,
ts.mon_loc_id AS location_id,
COALESCE(up.oris_code, spp.oris_code) AS oris_code,
COALESCE(u.unitid, sp.stack_name) AS unit_stack,
ms.system_identifier,
c.component_identifier,
ts.test_num AS test_number,
ts.gp_ind AS grace_period_indicator,
ts.test_type_cd,
ts.test_reason_cd,
ts.test_result_cd,
rp.period_abbreviation AS year_quarter,
ts.test_description,
camdecmps.format_date_hour(ts.begin_date, ts.begin_hour, ts.begin_min) AS begin_date_time,
camdecmps.format_date_hour(ts.end_date, ts.end_hour, ts.end_min) AS end_date_time,
ts.test_comment,
ts.span_scale_cd,
ts.injection_protocol_cd,
sac.submission_availability_cd,
sac.sub_avail_cd_description AS submission_availability_description,
sc.severity_cd,
sc.severity_cd_description AS severity_description
FROM camdecmps.test_summary ts
JOIN camdecmps.qa_supp_data sd USING (test_sum_id)
JOIN camdecmps.monitor_location ml ON ml.mon_loc_id::text = ts.mon_loc_id::text
JOIN camdecmpsmd.submission_availability_code sac USING (submission_availability_cd)
LEFT JOIN camdecmpsmd.reporting_period rp ON rp.rpt_period_id = ts.rpt_period_id
LEFT JOIN camdecmpsaux.check_session cs ON cs.chk_session_id::text = ts.chk_session_id::text
LEFT JOIN camdecmpsmd.severity_code sc USING (severity_cd)
LEFT JOIN camdecmps.monitor_system ms ON ms.mon_sys_id::text = ts.mon_sys_id::text
LEFT JOIN camdecmps.component c ON c.component_id::text = ts.component_id::text
LEFT JOIN camdecmps.stack_pipe sp USING (stack_pipe_id)
LEFT JOIN camd.unit u USING (unit_id)
LEFT JOIN camd.plant up ON up.fac_id = u.fac_id
LEFT JOIN camd.plant spp ON spp.fac_id = sp.fac_id;



ENDPOINT: GET /camd-services/admin/qa-maintenance/cert-events
Parameters: 
orisCode (required) 
unitStack 

Response:
{
    "certEventId": string
    "locationId": string
    "unitStack": string (show)
    "systemIdentifier": string (show combined with component – SysId/CompId if both)
    "componentIdentifier": string (show combined with system – SysId/CompId if both)
    "certEventCode": string (show)
    "certEventDescription": string
    "eventDateTime": string (show)
    "requiredTestCode": string (show)
    "requiredTestDescription": string
    "conditionalDateTime": string (show)
    "lastCompletedDateTime": string (show)
    "submissionAvailabilityCode": string
    "submissionAvailabilityDescription": string (show)
    "severityCode": string 
    "severityDescription": string (show)
}


Query: 

CREATE OR REPLACE VIEW camdecmps.vw_qa_cert_event_maintenance
AS SELECT 
qce.qa_cert_event_id AS cert_event_id,
qce.mon_loc_id AS location_id,
COALESCE(up.oris_code, spp.oris_code) AS oris_code,
COALESCE(u.unitid, sp.stack_name) AS unit_stack,
ms.system_identifier,
c.component_identifier,
cec.qa_cert_event_cd AS cert_event_cd,
cec.qa_cert_event_cd_description AS cert_event_description,
camdecmps.format_date_hour(qce.qa_cert_event_date, qce.qa_cert_event_hour, 0::numeric) AS event_date_time,
rtc.required_test_cd,
rtc.required_test_cd_description AS required_test_description,
camdecmps.format_date_hour(qce.conditional_data_begin_date, qce.conditional_data_begin_hour, 0::numeric) AS conditional_date_time,
camdecmps.format_date_hour(qce.last_test_completed_date, qce.last_test_completed_hour, 0::numeric) AS last_completed_date_time,
sac.submission_availability_cd,
sac.sub_avail_cd_description AS submission_availability_description,
sc.severity_cd,
sc.severity_cd_description AS severity_description
FROM camdecmps.qa_cert_event qce
JOIN camdecmps.monitor_location ml ON ml.mon_loc_id::text = qce.mon_loc_id::text
JOIN camdecmpsmd.submission_availability_code sac USING (submission_availability_cd)
JOIN camdecmpsmd.qa_cert_event_code cec USING (qa_cert_event_cd)
JOIN camdecmpsmd.required_test_code rtc USING (required_test_cd)
LEFT JOIN camdecmpsaux.check_session cs ON cs.chk_session_id::text = qce.chk_session_id::text
LEFT JOIN camdecmpsmd.severity_code sc USING (severity_cd)
LEFT JOIN camdecmps.monitor_system ms ON ms.mon_sys_id::text = qce.mon_sys_id::text
LEFT JOIN camdecmps.component c ON c.component_id::text = qce.component_id::text
LEFT JOIN camdecmps.stack_pipe sp USING (stack_pipe_id)
LEFT JOIN camd.unit u USING (unit_id)
LEFT JOIN camd.plant up ON up.fac_id = u.fac_id
LEFT JOIN camd.plant spp ON spp.fac_id = sp.fac_id;


ENDPOINT: GET /camd-services/admin/qa-maintenance/extension-exemptions

{
    "testExtensionExemptionId": string
    "locationId": string
    "unitStack": string (show)
    "systemIdentifier": string (show combined with component – SysId/CompId if both)
    "componentIdentifier": string (show combined with system – SysId/CompId if both)
    "fuelCode": string (show)
    "fuelDescription": string
    "extensionExemptionCode": string (show)
    "extensionExemptionDescription": string
    "hoursUsed": number (show)
    "spanScaleCode": string (show)
    "submissionAvailabilityCode": string
    "submissionAvailabilityDescription": string (show)
    "severityCode": string
    "severityDescription": string (show)
}

 Query:

CREATE OR REPLACE VIEW camdecmps.vw_qa_test_extens_exempt_maintenance
AS
SELECT 
tee.test_extension_exemption_id,
    tee.mon_loc_id AS location_id,
    COALESCE(up.oris_code, spp.oris_code) AS oris_code,
    COALESCE(u.unitid, sp.stack_name) AS unit_stack,
    ms.system_identifier,
    c.component_identifier,
    fc.fuel_cd,
    fc.fuel_cd_description AS fuel_description,
    eec.extens_exempt_cd AS extension_exemption_cd,
    eec.extens_exemp_cd_description AS extension_exemption_description,
    rp.period_abbreviation AS year_quarter,
    tee.hours_used,
    tee.span_scale_cd,
    sac.submission_availability_cd,
    sac.sub_avail_cd_description AS submission_availability_description,
    sc.severity_cd,
    sc.severity_cd_description AS severity_description
   FROM camdecmps.test_extension_exemption tee
     JOIN camdecmps.monitor_location ml ON ml.mon_loc_id::text = tee.mon_loc_id::text
     JOIN camdecmpsmd.submission_availability_code sac USING (submission_availability_cd)
     JOIN camdecmpsmd.fuel_code fc USING (fuel_cd)
     JOIN camdecmpsmd.extension_exemption_code eec USING (extens_exempt_cd)
     LEFT JOIN camdecmpsmd.reporting_period rp ON rp.rpt_period_id = tee.rpt_period_id
     LEFT JOIN camdecmpsaux.check_session cs ON cs.chk_session_id::text = tee.chk_session_id::
     LEFT JOIN camdecmpsmd.severity_code sc USING (severity_cd)
     LEFT JOIN camdecmps.monitor_system ms ON ms.mon_sys_id::text = tee.mon_sys_id::text
     LEFT JOIN camdecmps.component c ON c.component_id::text = tee.component_id::text
     LEFT JOIN camdecmps.stack_pipe sp USING (stack_pipe_id)
     LEFT JOIN camd.unit u USING (unit_id)
     LEFT JOIN camd.plant up ON up.fac_id = u.fac_id
     LEFT JOIN camd.plant spp ON spp.fac_id = sp.fac_id;



ENDPOINT: DELETE /camd-services/admin/qa-maintenance/cert-events/{id}
ENDPOINT: DELETE /camd-services/admin/qa-maintenance/test-summary/{id}
ENDPOINT: DELETE /camd-services/admin/qa-maintenance/extension-exemptions/{id}

Notes
Return status 200 on success
Delete QA test records from camdecmps.test_summary, camdecmps.qa_supp_data, camdecmpswks.qa_supp_data
Delete QA Cert Event records from camdecmps.qa_cert_event
Delete Test Extentions and Exemptions records from camdecmps.test_extention_exemption
The deletes will be done as raw queries so no entities need to be brought in

ENDPOINT: PUT /camd-services/admin/qa-maintenance/cert-events/{id}
ENDPOINT: PUT /camd-services/admin/qa-maintenance/test-summary/{id}
ENDPOINT: PUT /camd-services/admin/qa-maintenance/extension-exemptions/{id}

Notes:
Change the submission_availability_cd to “Required” in both global and workspace for cert event, or test extension exemption, or qa supp data
Return status 200 on success

**Comment by jwhitehead77** [comment]
@fanwari1 the following changes are needed...

**Test Summary view**
JOIN camdecmpsmd.reporting_period rp ON rp.rpt_period_id = ts.rpt_period_id
this should be a LEFT JOIN becasue test summary data either has begin/end date or a reporting period

**Test Ext/Exempt view**
rp.period_abbreviation AS "year_quarter",--SHOW in UI
JOIN camdecmpsmd.reporting_period rp ON rp.rpt_period_id = tee.rpt_period_id
missing from SELECT and JOINS and should be there since TEE has reporting period

**Comment by fanwari1** [comment]
@jwhitehead77 I made the updates to the original comments and the views
