### ISSUE TITLE
API: Update EM Submission GET Endpoint

### ISSUE THREAD

**Issue by acollad1** [US-EPA-CAMD/PI-1#5389]
As the ECMPS system I need to update the logic in the EM submission get endpoint to reflect the below logic:

- [x] If the Emissions status code is RECVD the status of the record is closed

- [x] If  the submission availability code is DELETED, CRITERR, or NOTSUB the status of the records is closed 
- [x] Add facilityName, reportingPeriodAbbreviation, and submissionTypeDescription (remove submissionTypeCode)
- [x] Determine why severityCode is returning null for all cases

**Comment by sdhawan16** [comment]
severityCode is returning null because the chk_session_id is NULL for all records in emission_evaluation table right now. To get the severityCodeDescription we join with the check_session table on chk_session_id and then with the severity_code table on severity_cd. Once the emission_evaluation table has the chk_session_id column populated we will be able to join over with the check_session table and get the severity codes.
