### ISSUE TITLE
E-O Sort/Filter: Aid in Wireframe User Validation Preparation

### ISSUE THREAD

**Issue by cvp-alexrobinson** [US-EPA-CAMD/PI-1#549]
### 💼 Assets
- [CAMPD Wireframe Prototype (Updated 2/8/21)](https://xd.adobe.com/view/8d3edf05-ae6e-49b6-99a2-e911027d6aab-d86d/?fullscreen&hints=off)
- [EASEY-Out Wireframe Prototype (Updated 2/5/21)](https://xd.adobe.com/view/12b35cd1-494e-4855-b075-1d40f9bcfca8-47e0/?fullscreen&hints=off)
- [EASEY-Out Wireframe Prototype](https://xd.adobe.com/view/dd4467ac-1c9d-445d-a335-854240486b4f-8817/?fullscreen&hints=off)

### 🧑‍💼 Stakeholders
- @tlageman-epa @JorjaComer @MoAdeyoju @nsameerun @staceyrenner @areighar @kstetsyuk

**Comment by tlageman-epa** [comment]
@cvp-alexrobinson Hey Alex, giving this a quick look over and it looks great! I'd be happy moving it forward to Ming if no one else has comments in addition to one small change and a note below. Thanks again for cranking this out!

1. I don't think it makes sense to have the data table in that pop-up message after the user hits preview because it is my understanding that we wouldn't be returning data for them to preview since it is too large. I think the pop-up message itself is enough.
2. Second, this is just something to make sure we note in the mod guide. Since XD appears to jump the screen around some when certain clicks are made, we should make it clear to users that this is a result of XD. I note this because we heard specific feedback from a number of users on AMPD and how they disliked that the page would jump down or to the top when they click certain things, so of course EASEY-Out won't be that way.

**Comment by cvp-alexrobinson** [comment]
@tlageman-epa — Makes sense... comments below.

1. I think this can be a key point of discussion with the user. I have a couple of questions about getting this updated.
- Should we grey out the "Preview" button for queries that have exceeded the limit—similar to the way it is before the two required fields are filled out? If we go that route, what would prompt the pop-up? Would the meter warning suffice?
- I'd like to clarify with @jwhitehead77 and the team on the preview functionality. I was thinking that it wasn't much bandwidth to serve previews from the larger queries. If so, we have an opportunity here to serve them the "email me the data link later" or even serve them suggested static datasets that closely align with their current query.
2. Yes, this can be added to the introduction that touches on the limitations of wireframes and these prototypes.

**Comment by tlageman-epa** [comment]
@cvp-alexrobinson Maybe for this round we just grey it out as you suggest and leave the message with the meter, so it wouldn't even go to a preview. My concern with the preview even if it didn't require much bandwidth is that unless I misunderstand something, our system would still be bearing the processing costs which is not ideal, and it might be more frustrating to the user that we are telling them they can't download the data even though we are showing some of it to them. We can discuss this more sometime next week. But for now, I think least effort for you and best option is as you described. Thanks!

**Comment by cvp-alexrobinson** [comment]
@tlageman-epa — Sounds like a plan.
