### ISSUE TITLE
CAMPD Sort/Filter: Revise Wireframes

### ISSUE THREAD

**Issue by cvp-alexrobinson** [US-EPA-CAMD/PI-1#550]
## Tasks
- [x] Revise wireframes for the hourly emissions sort/filter section of EASEY-Out
- [x] Review wireframes with EPA

## Design Assets
**Wireframes**
- [Prototype | CAMPD | Custom Data Download](https://xd.adobe.com/view/b48d25e4-895f-4f4e-9262-19c13c61374f-e1de/?fullscreen&hints=off)

**Archived Assets**
- [EPA CAMPD Live Design Link](https://xd.adobe.com/view/f4e20f96-ae68-414b-9325-a22d386aad98-a1b1/)
- [EASEY-Out Filter/Sort Wireframes v 1.4](https://xd.adobe.com/view/dd4467ac-1c9d-445d-a335-854240486b4f-8817/?fullscreen&hints=off)
- [EASEY-Out Filter/Sort Wireframes v 1.3](https://xd.adobe.com/view/4ef6ab5a-8af3-459d-9246-ffffbc6c9585-1ba5/)
- [EASEY-Out Filter/Sort Wireframes v 1.3 (alt)](https://xd.adobe.com/view/29f5b0e6-1e58-4f8b-9ab1-431071756430-7ca6/)
- [EASEY-Out Filter/Sort Wireframes v 1.2](https://xd.adobe.com/view/5b1e95b8-8e24-49d0-9a09-fa54e45ad485-0e4d/?fullscreen)

## Stakeholders:
@tlageman-epa 
@JorjaComer
@MoAdeyoju

**Comment by cvp-alexrobinson** [comment]
@tlageman-epa — Thanks for your feedback from last week. The wireframes have been modified and a new alternate view has been created that flows the data preview just under the form. Links are in the ticket description.

Best,
Alex

**Comment by tlageman-epa** [comment]
@cvp-alexrobinson following up from UX weekly. Here is the additional feedback. Let me know if you have any follow ups. Thanks!

- **Data query limit/indicator**: As discussed, we won't be able to let users download as much data as they want because it will be too much data. While we haven't determined the specific limit yet, we need to have a way of indicating to the status of the user's inputted request. That way they aren't inputting all their criteria, hitting preview and encountering an error that tells them "too much". So, please propose a way of indicating the "status" of the data request so that users know up front if they need to apply more filters, and/or that they may need to visit the static datasets to get larger data downloads. This status should probably include file size as well.
-  **"Daily Datasets" label**: Please just call it "Datasets" for now. 
- **Optional Criteria**: Please add an optional indicator to the remaining filter criteria, like you did for the required fields.
- **Program**: Please add add the criterion "Program". While this was not in the prototype requirements it will be in the MVP, and Ming would like to see this in the wireframe. This dropdown should allow for a user to pick multiple programs, and default to all programs.

**Comment by cvp-alexrobinson** [comment]
Thanks, @tlageman-epa!

**Comment by tlageman-epa** [comment]
@jwhitehead77 I am curious on your thoughts re: the Data Query limit indicator in my comment above, and how technically feasible that will be. Is what I described clear to you? Please let me know if you need me to clarify and we can hop on the phone. Thanks!

**Comment by tlageman-epa** [comment]
@cvp-alexrobinson  

Hey Alex, just heard from Jeremy that we'd want to know if users would find it useful to select for a specific emissions pollutant (apparently that's been heard in the past) Essentially, under Hourly Emissions there would be three sub-options for the pollutants (SO2, NOx, CO2) and if the user selected it, they would get a filtered set of data columns specific to that pollutant in the preview. If they just selected Hourly emissions, they'd get all as they do now. They should be able to pick multiple pollutants, not just one. Could you please add in those three pollutant options under the Hourly Emissions dataset option in the wireframe? Thanks and let me know if you have any questions.

**Comment by tlageman-epa** [comment]
@cvp-alexrobinson 

Per our discussion, Adobe XD lacks the capability for the user to fully interact with the wireframe. Therefore, we want the following scenarios to be included for the interviewees to be taken thru whether by stepping thru different frames (images) or walking them thru the limited interactivity of the filter criteria that we have already seen (i.e. user clicks on a field and it updates with predefined criteria). (Please don't take this as we don't want to see what other scenarios CVP UX team may have already been planning to walk through. Curious to see what direction we are heading in the Mod guide draft) 

1.	Scenario: User wants to retrieve all hourly emissions data for a single facility for a given year.
a.	The user selects one year of hourly emissions data 
b.	Then they pick one facility. 
c.	The state field auto-updates with the respective state
d.	The user then previews the data and it executes successfully.

2.	Scenario: User wants to retrieve all hourly emissions data for a single state for a given year.
a.	The user selects one year of hourly emissions data
b.	Then they skip the facility field and pick one state 
c.	The facility field auto-updates with the respective facilities
d.	The user tries to preview the data but a message pops up saying: “You have requested too large of a dataset, please refine your criteria or visit the static datasets for larger data downloads” 
e.	We ask user how they would handle this, would they refine, split up requests, go to static datasets, other?

3.	Scenario: User wants to retrieve all hourly emissions data for all states and facilities for a given year.
a.	The user selects one year of hourly emissions data
b.	Then they pick all states or all facilities and hits preview and receives the same message as in 2a (no selection in states/facilities would also achieve this – so we will also assess if “no selection means select all” is an intuitive concept or not)
c.	Same questions as 2e

4.	A screen that shows a dynamic request size indicator that would update as the user picked their criteria. (We recognize there will be coding/other concerns behind this as already shared, but we'd still like to provide this to users to get their feedback)
a.	This would just be a couple of images of the wireframe with the status indicator in different states based on the data selection (i.e. using the scenarios above to represent a passing and a failing request)

Please take the liberty to propose your idea of what that dynamic status indicator might look like in the wireframe/image, whether it is a file size, number of records, or something else.

Lastly, I know we had taken out the "All" checkboxes for the unit characteristics, but we'd like to see an option like this for the Facility and States dropdowns in one of the scenarios to see how users react. In this case, the default value in the field for states, for example, is not blank but actually shows the "All States" box like in the unit Characteristics for "All Boilers". The dropdown would have an option for "All states" that is pinned to the top of the search results in case a user decides to re-toggle that option. So one of the scenarios above should have this all types for facility/states this way, while the others maintain the blank field default = all states/facilities. Hopefully, that makes sense. If not, can try to clarify Monday after the other changes.

**Comment by kstetsyuk** [comment]
@cvp-alexrobinson @tlageman-epa @areighar 

Alex,

Below are actions/changes for the hourly emissions wireframes we captured from our meeting Friday. We ideally would like the wireframe updates by the end of day Tuesday so EPA can check Wednesday morning before refinement (2/24).

If you have any questions, please let us know.

**Action Items to Decide on Further Changes** 
•	Need to have a larger conversation with Mike/Jason/Travis what our “cap” is going to be for downloading data. 
•	Alex will talk to Anthony about 508 compliance of current wireframe and proposed changes. 
•	Andrew is working on gathering ideas for helper text.
**Changes to Be Made** 
•	“Data On-Demand" will be called “Custom Data Download” 
•	“Dataset” field will be called “Data Type” 
•	Make Data Type the only field that shows up upon arrival to page, which ensures this required field will be the first one to be modified, which then triggers the reveal of all remaining categories associated with Data Type selected. 
•	Remove MATS as an option under “Data Type” 
•	Add scroll bars to all applicable fields. 
•	Instead of auto population when a state is selected, we’d like to see the facilities field display, for example, “4 facilities selected” and vice versa with states. 
•	On the dropdowns for facilities and states, we like how the user must begin typing before seeing options. We’d like to have a cap on what is scrollable for the facilities field when the user begins typing. Our idea of this cap being the number of facilities of the state that has the most facilities to actually be scrollable. This is to avoid having to scroll through hundreds of options. 
•	Query gauge can be removed, instead focusing on the graying out of the preview/download button plus helper text to indicate if a query is too large.
•	Have data preview feature first 100 rows with helper text that indicates this, as well as showing the file size of the query, and number of rows.

**Comment by kstetsyuk** [comment]
@cvp-alexrobinson 

Hey Alex, just as a reminder, please update the pop-up warning message.

New text -

Your custom data query is too large.
Try using additional filters or visit the Datasets page for larger data downloads.

Thanks!

**Comment by cvp-alexrobinson** [comment]
@kstetsyuk @tlageman-epa — Here's a look at what the Data Type would look like as a modal. Any red flags?

![Screen Shot 2021-02-25 at 8.39.14 AM.png](https://images.zenhubusercontent.com/5f7481b4ffe2db3478776559/b2462dca-937e-4ec4-a217-7a87a65c4965)

Also, wanted some feedback on a possible enhancement to the Allowances and Compliance Data Types. These sub-data types are just examples only, but I hope it gives us something to think about when diving into these remaining data types.

![Screen Shot 2021-02-23 at 3.50.38 PM.png](https://images.zenhubusercontent.com/5f7481b4ffe2db3478776559/d565b53c-a841-4214-850c-9dfc105d6fe6)

**Comment by cvp-alexrobinson** [comment]
@tlageman-epa Here's the XD design link I'm currently working on...
[EPA CAMPD Live Design Link](https://xd.adobe.com/view/f4e20f96-ae68-414b-9325-a22d386aad98-a1b1/)

**Comment by cvp-alexrobinson** [comment]
@kstetsyuk @tlageman-epa The latest... 
https://xd.adobe.com/view/f4e20f96-ae68-414b-9325-a22d386aad98-a1b1/?fullscreen

**Comment by cvp-alexrobinson** [comment]
@kstetsyuk @tlageman-epa — Still noodling around with the screens after the CDD data type picker, so it doesn't go any further.
https://xd.adobe.com/view/f4e20f96-ae68-414b-9325-a22d386aad98-a1b1/

**Comment by cvp-alexrobinson** [comment]
@kstetsyuk @tlageman-epa — Here's the rough prototype for the new landing to filter flow. I understand that there are conversations that we need to have about the data type and data subtype flows but I just wanted to share a work in progress.
https://xd.adobe.com/view/f4e20f96-ae68-414b-9325-a22d386aad98-a1b1/

**Comment by cvp-alexrobinson** [comment]
@kstetsyuk @tlageman-epa — Here's a new link with the intro flow all the way to the "additional" filters screen. Those filter panels have yet to be fleshed out. Hopefully this gives you enough for the meeting tomorrow.
https://xd.adobe.com/view/739bf3e8-1bd1-4647-9210-9a10d749115e-26c8/

**Comment by cvp-alexrobinson** [comment]
@kstetsyuk @tlageman-epa — Here are draft wire links to two mobile breakdowns. I think I'm going to make these a little more compact than they actually are, still a work in progress.

**[Mobile - Desktop - Min](https://xd.adobe.com/view/18d9766f-ab09-4e30-93c5-d600c66be6bd-4d8a/)**
- This is the smallest desktop width for the USWDS framework.
- Menu folds up, data type and filter are separate panels triggered by new buttons.

**[Mobile - Tablet - Min](https://xd.adobe.com/view/e73db81f-3a7b-44ed-9f1e-f4d927fbd426-b26e/)**
- This is the smallest tablet width for the USWDS framework.
- Title shrinks, menu folds up, data type and filter are separate panels triggered by new buttons.

Here's the proposed language for devices smaller than the tablet minimum width. 
_This tool allows users to create custom queries of emissions, allowance, compliance and/or facility information. This tool is only accessible using desktop and tablet devices._
No functionality will be accessible beyond the intro page.

![Screen Shot 2021-03-15 at 5.18.00 PM.png](https://images.zenhubusercontent.com/5f7481b4ffe2db3478776559/c0e5ba99-f3c1-4d09-8fd3-08a23d3e972d)

**Comment by cvp-alexrobinson** [comment]
@kstetsyuk @tlageman-epa — Building out filter panels. Currently adding Unit Types.

![Screen Shot 2021-03-22 at 5.00.54 PM.png](https://images.zenhubusercontent.com/5f7481b4ffe2db3478776559/f75b26b9-8bd2-47e1-ad23-4de98cc8a6ce)

**Comment by cvp-alexrobinson** [comment]
@kstetsyuk @tlageman-epa — New links in the description.

**Comment by cvp-alexrobinson** [comment]
@kstetsyuk @tlageman-epa — [Prototype](https://xd.adobe.com/view/129b1991-bd2b-475f-8f90-8e14d430c2ff-47c8/)

- This should take you to Emissions, Hourly emissions with a top-level view of the panels.
- This also takes you into both Allowance, Holdings UXR scenarios
- It's still pretty guided, but kick the tires a bit.
- I even added some keyboard controls.

Note: I haven't made the custom data preview tables yet so they're still displaying the emissions tables. I'll take care of those on Monday.

**Comment by cvp-alexrobinson** [comment]
@kstetsyuk @tlageman-epa — The data preview tables now match the filters in both scenarios. 
https://xd.adobe.com/view/129b1991-bd2b-475f-8f90-8e14d430c2ff-47c8/screen/805a95a3-d834-4979-8795-74628476c219

**Comment by cvp-alexrobinson** [comment]
@tlageman-epa @kstetsyuk @staceyrenner — [Here's the latest prototype link](https://xd.adobe.com/view/b48d25e4-895f-4f4e-9262-19c13c61374f-e1de/?fullscreen&hints=off). I was able to get all of those changes implemented. Let's do a little internal testing, walking through the scenarios on different machines and browsers. Please log any issues here in this ticket.

**Comment by kstetsyuk** [comment]
@cvp-alexrobinson 
Thanks! I've gotten (so has Travis) a blank screen at random points (more consistently at the data subtype selection for emissions and the facilities filter for allowances), but after refreshing and closing out some things on my machine, that seemed to help. However, I am still getting a blank screen when trying to click the facilities filter for allowances.
Overall, it looks great! Thanks for updates!

**Comment by kstetsyuk** [comment]
@cvp-alexrobinson 
Was able to get passed facilities by refreshing some, but the typing in the vintage years filter is not working for me.

**Comment by cvp-alexrobinson** [comment]
@kstetsyuk — Trying to republish to see if that helps.
