### ISSUE TITLE
CAMPD | Create High-Fidelity UI Design

### ISSUE THREAD

**Issue by cvp-alexrobinson** [US-EPA-CAMD/PI-1#551]
## 📋 Objectives
Create high-fidelity screens, or mockups, for the CAMPD platform. The following mockups will be produced for review and revision:
- CAMPD landing page (Home)
- CAMPD Data landing page (Home/Data)
- CAMPD Custom Data Download (Home/Data/Custom Data Download)
- CAMPD Custom Data Download, Emissions, Hourly Emissions (Home/Data/Custom Data Download/Emissions, Hourly Emissions)
  - Data Subtype selection
  - Sidebar with filters
  - Filter panel
  - Filter selections with breadcrumbs
  - Data preview

## 📂 Assets
_Links to design assets_

## 🤝 Stakeholders
@tlageman-epa @JorjaComer @MoAdeyoju

**Comment by cvp-alexrobinson** [comment]
@tlageman-epa @JorjaComer @MoAdeyoju — I noticed this ticket was still active but these screens have been designed as a part of the May demo design efforts back in April. Please let me know if you have any issues with me closing this ticket out.

Best,
Alex

**Comment by tlageman-epa** [comment]
The Data Landing page has not been designed yet, otherwise all the items in this ticket appear to be completed. This item is reflected in the updated design priority list we sent last week (5/26). So as long as this is captured and handled in the Product Design Meetings, I am fine with closing this ticket out.

@cvp-alexrobinson @JorjaComer @MoAdeyoju

**Comment by JanellC** [comment]
This ticket is completed. Additional high fidelity designs will be discussed and prioritized during CAMPD Product Design meetings.
