### ISSUE TITLE
Dependabot: @adobe/css-tools Regular Expression Denial of Service (ReDOS) while Parsing CSS

### ISSUE THREAD

**Issue by JanellC** [US-EPA-CAMD/PI-1#5624]
## Context

Moderate issue depedabot issue in the US-EPA-CAMD/easey-ecmps-ui and US-EPA-CAMD/easey-campd-ui repos 

https://github.com/US-EPA-CAMD/easey-campd-ui/security/dependabot/52

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdXg2IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--654ba633eb91684c6303a32776d3816e2c58502f/image.png)

**Comment by JanellC** [comment]
Based on 9/19 Refinment discussion, DPC will work on this dependabot issue. Because this is not a high or severe issue, this is not a high priority item.

**Comment by hamezene** [comment]
Need to debug this issue

**Comment by hamezene** [comment]
This issue seems to be fixed - Justin will add screengrab and verify fix with Jason before closing ticket.

**Comment by ergjustin** [comment]
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBczNxIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--69ee96cc582a97029b5ae8eada8beb52ff7b1cb0/Dependanbot.PNG)

**Comment by jwhitehead77** [comment]
this has been addressed with dependabot PR being merged into develop for both campd and ecmps. If you look at security tab and go to Dependabot you will see that the issue is no longer listed. We should not be creating tickets for these unless Dependabot is not able to create the PR as this duplicates efforts.
