### ISSUE TITLE
Monitoring Plan 508 Wireframe Review

### ISSUE THREAD

**Issue by cvp-alexrobinson** [US-EPA-CAMD/PI-1#563]
### Tasks
- [x] Review wireframes with @aprematta for 508 feedback.

**Comment by cvp-alexrobinson** [comment]
@aprematta — Here are my notes from our call. Please feel free to add your own comments to this ticket.

- The coding of the UI tabs will be important. They need to be "tab-able."
- Be sure to discuss tab order with dev and UX team—especially with multiple menus, tables, and accordions.
- Make sure that scrollable areas can be scrolled using a keyboard.
- "Open" buttons or links should be labeled in the code with what they're actually opening. E.g. "Open Power Plant."
- Make the tabs only openable from the actual "open" buttons, anything else would be inaccessible or confusing
- Form fields should only submit input when a user has told it to submit.
- Make sure that sections like the pagination area have hidden headings that identify them as such for screen readers.
- The external "show/hide inactive" toggle method is preferred.

CC @karenhwwoo @MoAdeyoju @jwhitehead77 @addisgmichael @Qb10

**Comment by aprematta** [comment]
Hey @cvp-alexrobinson ,

As we discussed, the wireframes as is are ok but there will be necessary coding required to make them compliant in the final application. There are also decisions that would be easier to implement. Here are my notes:

The coding of the UI tabs will be important. They need to be "tab-able."

- Be sure to model the tab coding against the aria specs, here are some resources
- https://www.w3.org/TR/wai-aria-practices-1.1/#tabpanel
- https://www.w3.org/TR/wai-aria-practices-1.1/examples/tabs/tabs-1/tabs.html
- https://dequeuniversity.com/library/aria/tabpanel
- http://accessibility.athena-ict.com/aria/examples/tabpanel2.shtml

Be sure to discuss tab order with dev and UX team—especially with multiple menus, tables, and accordions.

- Tab order should be logical, up to down, left to right
- Make sure the tab order is based on the order in the DOM, do not use tabindex because the order must also be logical in the DOM for screen readers

Make sure that scrollable areas can be scrolled using a keyboard.

- If specific keystrokes are necessary to scroll, be sure to put visible directions on the page to communicate the keystrokes to the user

"Open" buttons or links should be labeled in the code with what they're actually opening. E.g. "Open Power Plant."

- Yes, visibly it's ok to have the buttons say 'Open Tab' but programmatically it should be something like 'Open Tab for <facility name>. This can be done with an aria label. See example 1 on https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Techniques/Using_the_aria-label_attribute. 

Make the tabs only openable from the actual "open" buttons, anything else would be inaccessible or confusing

- This would simplify. If the whole row is clickable, then just make sure that the keyboard only tabs to the open tabs buttons

Form fields should only submit input when a user has told it to submit.

- This would simplify, otherwise you would need a visible message saying that a change on the page will occur when interacting with the forms, see https://www.w3.org/TR/2016/NOTE-WCAG20-TECHS-20161007/G13

Make sure that sections like the pagination area have hidden headings that identify them as such for screen readers.
The external "show/hide inactive" toggle method is preferred.

-  Correct, pagination in general will need care in keyboard accessibility and coding. See https://www.a11ymatters.com/pattern/pagination/ for an example. Right now one problem is that if a keyboard user activates a pagination page, 3 for example, visually the table is shifted, but when tabbing back, it goes to the last row of the table.

Other Notes

- Be sure the Close tab option (X) is keyboard accessible and that it also has an accessible name (Close tab instead of X)
- Be sure forms have programmatic names, right now they have visible labels but the labels are not coded with label tags and associated to the forms, see https://webaim.org/techniques/forms/controls
-  The dropdown with the active/inactive collapsible elements will be tricky, I'd suggest changing it to a checkbox outside that filters the dropdown values
- Sortable tables need to be keyboard accessible and coded so that screen readers know if the column is sorted by ascending or descending, examples https://www.w3.org/TR/wai-aria-practices-1.1/examples/grid/dataGrids.html, https://dequeuniversity.com/library/aria/table-sortable

CC @karenhwwoo @MoAdeyoju @jwhitehead77 @addisgmichael @Qb10
