### ISSUE TITLE
Bug: Monitoring Plan Qualifications Scroll Bar

### ISSUE THREAD

**Issue by acollad1** [US-EPA-CAMD/PI-1#5650]
Based on the output of spike ticket 5611 need to resolve the responsiveness issue in the monitoring plan qualification section which includes the scroll bar not functioning

**Comment by cw-cvp** [comment]
Bug details:
When using the 'sortIcon' and 'fixedHeader' props of [react-data-table-component](https://react-data-table-component.netlify.app/?path=/docs/api-props--page), the the vertical scrolling only happens with the scrollwheel when the user's mouse pointer is directly over the data table headers.
This happens in Chrome and Microsoft Edge but not in Firefox.
Removing the 'sortIcon' and 'fixedHeader' props fixes the issue.

When using an SVG (e.g. ArrowDownwardSharp or inline svg) the bug is present, instead using a p or img element the bug is not present.
Scrolling with arrow keys or laptop touchpad works as expected.
The modal-body div in Modal.js (~line 138) receives onWheel and onWheelCapture events whether scrolling happens or not.
This bug occurs in any Monitoring Plan section using DataTableRender.js in its modal body. (e.g. Qualifications and Systems)
[Fixes ](https://github.com/US-EPA-CAMD/easey-ecmps-ui/pull/1261)for Systems section have been pushed alongside Qualification fixes.

**Comment by mosesdeeCVP** [comment]
Part of the problem was fixed. There is another bug that will be handled in this ticket: [Bug: MP Qualifications Horizontal Scroll Bar #5692](https://app.zenhub.com/workspaces/ecmps-prod-team-64623d2269329d0c96ba04f3/issues/gh/us-epa-camd/easey-ui/5692)
