### ISSUE TITLE
Sonar Cloud Bug: Monitoring Plan

### ISSUE THREAD

**Issue by acollad1** [US-EPA-CAMD/PI-1#5657]
- [ ] Remediate sonar cloud bug in monitoring plan 
https://sonarcloud.io/organizations/us-epa-camd/projects

- [ ] Resolving promises reference:
promises.push( new Promise((resolves, rejects) => {}) ) -> Needs to become promises.push(async function signature)

**Comment by hamezene** [comment]
@shahbazkhan1999 will do peer review

**Comment by shahbazkhan1999** [comment]
@ergjustin please check comment on PR

**Comment by bchofor** [comment]
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdzFhQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--47da5341e11a43cb9bf9612c4ac8bcf6da41e609/image.png)

Sonar Cloud Bug: Monitoring Plan#5657 failed

**Comment by ergjustin** [comment]
[SONAR IMAGE](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMGhhQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5c7fd878523aaa8d264fa953a84d3853ce1a616d/sonar.PNG)


This ticket was completed in September last (3 weeks ago) that time it is fully clear and code coverage is above 70%. After completed this, codes were added in this repo and not added unit test, so that reason code coverage reduced.
