### ISSUE TITLE
Create submissions endpoint 

### ISSUE THREAD

**Issue by JanellC** [US-EPA-CAMD/PI-1#5697]
## Context 

Create emissions submissions endpoint. 
Requirements are linked in the following document: https://usepa.sharepoint.com/:w:/r/sites/CAMDCVPTeam/Shared%20Documents/Integration%20Coordination/ECMPS%202.0%20Additional%20API%20Endpoints%20from%20ERG.docx?d=w296309d4a7d24329836ad2f86315057d&csf=1&web=1&e=ubYUYn

**Comment by djw4erg** [comment]
**Testing Issues**:

1. The endpoint returns submission data that are not for emission reports.  It looks like this would be PROCESS_CD = "HOURLY", but was FILE_TYPE_CD = "EM" in ECMPS 1.0.  No emission submissions seem to exist in the ECMPS 2.0 development database.
2. The endpoint returns submission data that are note loaded (official) or CRIT 1.  I believe that loaded would be STATUS_CD = "COMPLETE" and Kyle indicated that loading CRIT 1 does not occur in ECMPS 2.0.  The endpoint seems to return submission with STATUS_CD = "WIP", for In Progress.
3. Need to confirm that Chris Worley about the removal of CRIT 1 submissions to ensure that he has the same understanding as Kyle.

**Comment by JanellC** [comment]
Kyle addressed the updates above. Let us know if this ticket is good to go or if we need to make any more updates @djw4erg

**Comment by djw4erg** [comment]
### 2023-10-24 Testing Results:

URL: https://api.epa.gov/easey/dev/camd-services/submission/last-updated?date=2023-03-01

- Both the return timestamp and timestamps in the data include the time zone notation.  Based on previous endpoints I believe that the timestamps should be in EST.  We need to discuss.
- Since the submission table structure is different for ECMP 1.0 and 2.0, we need to know which table columns are compared to the passed timestamp?  We may need to discuss.
  - CAMDECMPS.EMISSION_EVALUATION.LAST_UPDATED?
  - CAMDECMPSAUX.SUBMISSION_QUEUE.SUBMITTED_ON?
  - CAMDECMPSAUX.SUBMISSION_SET.SUBMITTED_ON?
 
Still need to check the following:

1. The endpoint returns submission data that are not for emission reports. It looks like this would be PROCESS_CD = "HOURLY", but was FILE_TYPE_CD = "EM" in ECMPS 1.0. No emission submissions seem to exist in the ECMPS 2.0 development database.
2. The endpoint returns submission data that are note loaded (official) or CRIT 1. I believe that loaded would be STATUS_CD = "COMPLETE" and Kyle indicated that loading CRIT 1 does not occur in ECMPS 2.0. The endpoint seems to return submission with STATUS_CD = "WIP", for In Progress.
3. Need to confirm that Chris Worley about the removal of CRIT 1 submissions to ensure that he has the same understanding as Kyle.

**Comment by JanellC** [comment]
@Kyle-Herceg fixed the issues above. @djw4erg
