### ISSUE TITLE
Implement cross-browser testing with BrowserStack

### ISSUE THREAD

**Issue by david-cvp** [US-EPA-CAMD/PI-1#575]
Follow up from research #486

- [ ] Implement crossbrowser into Easey-Testing package 

Browser requirements:
Chrome v86
MS Edge v86
Firefox v80
Safari v13

**Comment by david-cvp** [comment]
EPA will discuss with POs how to approach cross-browser testing and prioritization of different browser use

**Comment by ibarra-michelle** [comment]
@davidkwartler @YefimAbramsonCVP do you recall a date or do you have a date you would prefer to have a response by?

**Comment by david-cvp** [comment]
@ibarra-michelle No, we don't have a specific need-by date but we would probably like to get this done sometime in PI 3.

**Comment by david-cvp** [comment]
Michelle will discuss with POs on 3/1

**Comment by ibarra-michelle** [comment]
@davidkwartler @YefimAbramsonCVP - let's move ahead with testing the following browsers in the following priority:
1. Chrome v86
2. MS Edge v86
3. Firefox v80
4. Safari v13

In the future, let's revisit if we need to test all of these browsers and/or reprioritize what browsers we test since (1) Chrome and MS Edge are based on Chromium and (2) we can observe what browsers our EASEY-IN beta and CAMPD users use.

**Comment by MaeganWood64** [comment]
- Was deprioritized but moved into PI ^, looking into more efficient cross browser testing

**Comment by MaeganWood64** [comment]
- Will be looked into during I&P sprint
