### ISSUE TITLE
Bug: Emissions View Render Issue 

### ISSUE THREAD

**Issue by acollad1** [US-EPA-CAMD/PI-1#5776]
Issue:
When you pick your filters and apply filters in the emissions view a blank table appears after loading before the data is actually filled in the table.

**Comment by mosesdeeCVP** [comment]
The below is an example of a facility that has this bug. This issue is in both Global and Workspace:

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMnlhQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6ea252c889f72f1388bd6f7a8866c74983b2122a/Emissions%20View%20Render%20Issue%20%235776.png)

**Comment by mosesdeeCVP** [comment]
Spinner is now active and functioning in the UI:

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK1NmQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f7c17af3426d81b0484348afe9802508846648cf/Emissions%20View%20Render%20Issue%20%235776.png)
