### ISSUE TITLE
RETEST:Last modified by field not populating properly  in BETA

### ISSUE THREAD

**Issue by JanellC** [US-EPA-CAMD/PI-1#5892]
## Context 
 
In the BETA Enviornment, the "last modified by" field displays as WINMGMT instead of the last user who modified the data. Last modified by field was WINMGMT after import from historical and then missing after submission (expected behaviour is that it is the user who modified the data)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOXlhQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--947105c25bc42f559b26e8f12e183a636e7fb71b/image.png)

## Steps to Reproduce 

1. Navigate to the BETA environment and Log into ECMPS 
2. Check out a facility (Oris Code: 55418 config: CT-1) 
3. Navigate to QA or Emissions module and import data from historical 
4. Navigate to evaluation module and find the recently imported data 

 The "last modified by" field displays as WINMGMT instead of the last user who modified the data. The expected behaviour is that the last modified by" field is the user who modified the data.

**Comment by JanellC** [comment]
Pulling this bug back. Tech Team will need to make some backend fixes before this issue can be addressed

**Comment by esaber76** [comment]
Note: WINMGMT likely showing in tst and beta for 2023 Q3 windows because a job keeps reopening them.

On dev, check Last Modified By field in Evaluate screen for:

- MP with no changes (revert to official)
- QA test with closed window
  - Import from historical
  - Import from file
- EM file with closed window
  - Import from historical
  - Import from file
- MP with open window
  - Manual change in interface
  - Import from file
- QA test with open window
  - Import from historical
  - Import from file
- EM file with open window
  - Import from historical
  - Import from file
- Evaluate and submit MP, QA, EM data
- Revert to official and check column again after submissions

- Repeat tests in tst environment.
- Repeat tests in beta environment.

**Comment by esaber76** [comment]
The original issue reported in this ticket was related to WINMGMT displaying in the beta environment and the Evaluate screen. This is the same in the test environment for 2023 Q3 windows because a job keeps reopening them.

Closing this ticket. New findings related to this field are documented in #6251.
