### ISSUE TITLE
Emissions data display in the quarterly view and hourly seems incorrect

### ISSUE THREAD

**Issue by ntknguyen** [US-EPA-CAMD/PI-1#6180]
The value displaying in the Quarterly Summary View is not matching with the value in the Summary Value table.   
Example:
1. Import 2023 Q3 emissions from historical for oris 8906, CP30, 31RH, 31SH
2. Select Quarterly Summary View for 31RH then apply filter
3. The total op hours in the quarterly reported row should be 1507 not 1753.
4. The total op time hours should be 1502.41 not 1748.58

The hourly value seems incorrect.
1. Repeat step 1 
2. Select Hourly NOx Rate CEMS View the apply filter
3. Date/Hour column display 7/17/2023 12:00 as the first row.  The first row should show 7/1/2023 00:00 as the first row.

**Comment by lgiannini1** [comment]
Was not able to replicate issue on dev site retrieving 2023 Q3 ORIS 8906 8906, CP30, 31RH, 31SH. Op hours/ op time totals were matching values from camdecmps.summary_value table and values in 1.0. 

I think the difference in quarterly summary values are due to submissions made previously for regression testing on the tst site. The quarterly reported op hours, op time, heat input, and NOx Rate values for 2023 Q3 are identical to the values in 2022 Q3 on tst.

**Comment by ntknguyen** [comment]
The total op hours value display in ECMPS test is 1753, total op time is 1748.58.  FACT, CAMPD, and the SUMMARY-VALUE table shows the same value, 
<img width="431" alt="CAMDBSP-2023q3-SummaryValue-Astoria-CP30" src="https://github.com/US-EPA-CAMD/easey-ui/assets/17596531/bfe9d8f6-14e3-47f1-a4ca-f523d3f0a509">
![CAMPD-Astoria-CP30-31RH-31SH-2023Q3-quarterly summary](https://github.com/US-EPA-CAMD/easey-ui/assets/17596531/4bd46d14-4531-4a6b-b713-b7508439c964)
<img width="607" alt="FACT-Astoria-CP30-31RH-31SH-2023Q3-quarterly summary" src="https://github.com/US-EPA-CAMD/easey-ui/assets/17596531/dea93fea-c6e6-410e-8978-b7d14e7ce754">
<img width="588" alt="ECMPSTest-2023q3-SummaryValue-Astoria-CP30" src="https://github.com/US-EPA-CAMD/easey-ui/assets/17596531/e5b298bf-6d3f-4422-a4a8-fb9bba192489">

**Comment by alangmaid** [comment]
Determined to not be an issue. Data were accurately different among environments
