### ISSUE TITLE
Research: Submission end points need to verify submission

### ISSUE THREAD

**Issue by annalbrecht** [US-EPA-CAMD/PI-1#6193]
The API needs to check the conditions before accepting submissions (post, put, and delete end points).

- Monitoring plan
- QA
- QCE
- TEE
- Emissions
- MATS Bulk files (PDF, Json, XML)

**Comment by annalbrecht** [comment]
Requirements need to be determined and documented.

**Comment by djw4erg** [comment]
# Submission Condition Notes

## Handled in #6328

### General Notes

1. ECMPS 1.0 has PENDING_STATUS_CD columns in the MONITOR_PLAN (MP), EMISSION_EVALUATION (EM), QA_SUPP_DATA (QAT), QA_CERT_EVENT (QCE), and TEST_EXTENSION_EXEMPTION (TEE) tables.  The column usually contains nulls, but contains 'PENDING' or 'PENDUP' when the data has been submitted but has not been loaded into the actual data tables.
   1. The 'PENDING' or 'PENDUP' statuses are akin to having started a submission job that has not completed.  However, **ECMPS 2.0 does not appear to set these statuses**.
2. ECMPS 1.0 has an IN_SYNCH_FLG column in the client SYNCHRONIZATION_MANAGEMENT table that indicates whether the client version of the table matches the host version.  The SYNCHRONIZATION_MANAGEMENT table is used to determine whether data associated with specific monitoring plans in individual client ECMPS databases need to be updated.  In ECMPS 2.0, the number of client databases are akin to the lone CAMDECMPSWKS schema.
   1. **Because only one source of submissions exists, the need to check for being in-synch no longer exists**.

### Monitoring Plan (MP) Submission Conditions

1. MONITOR_PLAN.**SUBMISSION_AVAILABILITY_CD** equals '**REQUIRE**' **or** MONITOR_PLAN.**UPDATED_STATUS_FLG** equals '**Y**'.
2. MONITOR_PLAN.**NEEDS_EVAL_FLG** equal '**N**'.
4. Linked CHECK_SESSION.**SEVERITY_CD** is not null (or missing row) and not '**FATAL**'.
   1. **Need to determine what to do if **SEVERITY_CD** is '**CRIT1**'.**

### Emission Report (EM) Submission Conditions

1. EMISSION_EVALUATION **SUBMISSION_AVAILABILITY_CD** equals '**REQUIRE**', or **SUBMISSION_AVAILABILITY_CD** equals '**GRANTED**' and UPDATED_STATUS_FLG equals '**Y**'.
2. EMISSION_EVALUATION.**NEEDS_EVAL_FLG** equal '**N**'.
4. Linked CHECK_SESSION.**SEVERITY_CD** is not null (or missing row) and not '**FATAL**'.
   1. **Need to determine what to do if **SEVERITY_CD** is '**CRIT1**'.**

### QA Test (QAT) Submission Conditions

1. Related QA_SUPP_DATA.**SUBMISSION_AVAILABILITY_CD** equals '**REQUIRE**', or QA_SUPP_DATA.**SUBMISSION_AVAILABILITY_CD** equals '**GRANTED**' and TEST_SUMMARY.UPDATED_STATUS_FLG equals '**Y**', or QA_SUPP_DATA row does not exist and TEST_SUMMARY.UPDATED_STATUS_FLG equals '**Y**'.
2. TEST_SUMMARY.**NEEDS_EVAL_FLG** equal '**N**'.
3. Linked CHECK_SESSION.**SEVERITY_CD** is not null (or missing row) and not '**FATAL**'.
   1. **Need to determine what to do if **SEVERITY_CD** is '**CRIT1**'.**

### QA Certification Event (QCE) Submission Conditions

1. QA_CERT_EVENT.**SUBMISSION_AVAILABILITY_CD** equals '**REQUIRE**' **or** QA_CERT_EVENT.**UPDATED_STATUS_FLG** equals '**Y**'.
2. QA_CERT_EVENT.**NEEDS_EVAL_FLG** equal '**N**'.
3. Linked CHECK_SESSION.**SEVERITY_CD** is not null (or missing row) and not '**FATAL**'.
   1. **Need to determine what to do if **SEVERITY_CD** is '**CRIT1**'.**

### Test Extension and Exemption (TEE) Submission Conditions

1. TEST_EXTENSION_EXEMPTION.**SUBMISSION_AVAILABILITY_CD** equals '**REQUIRE**' **or** TEST_EXTENSION_EXEMPTION.**UPDATED_STATUS_FLG** equals '**Y**'.
2. TEST_EXTENSION_EXEMPTION.**NEEDS_EVAL_FLG** equal '**N**'.
3. Linked CHECK_SESSION.**SEVERITY_CD** is not null (or missing row) and not '**FATAL**'.
   1. **Need to determine what to do if **SEVERITY_CD** is '**CRIT1**'.**

## Handled in #6346 

### MATS Bulk Files (PDF, JSON, XML) Submission Conditions (from ECMPS 1.0)

**Need to determine the actual ECMPS 2.0 conditions based on metadata decisions that have not been made.**

- Averaging Plan, Facility State, Monitoring Location, Report Type, Facility Address Line 1, Facility City, and Facility Zip Code are required.
- Pollutant and Test Method are required for specific Report Types.
- Test Number, Test Comment and Facility Address Line 2 must contain ASCII readable characters.
- Facility Zip Code must contain five characters.
- Facility Zip Plus 4 must contain four characters.
- User must confirm the Responsible Official information.
- The user must of selected a file to submit.
