### ISSUE TITLE
Research: Determine if Submission Process uses DB transactions

### ISSUE THREAD

**Issue by annalbrecht** [US-EPA-CAMD/PI-1#6354]
Investigate to see whether the Submission Process uses DB transactions. If not, create a new ticket to modify the submission process to make database transactions.

**Comment by maxdiebold-erg** [comment]
The submission process **does** indeed use a transaction when calling the `copy_*_from_workspace_to_global` procedures. In the **`SubmissionProcessService`** of `easey-camd-services`, the procedure calls are built in the `buildTransaction` method, then executed inside a single database transaction in the `successCleanup` method.

There are status updates made outside of the transaction to the following tables:
- _camdecmsaux.submission_queue_
- _camdecmpsaux.em_submission_access_
- _camdecmpswks.monitor_plan_
- _camdecmpswks.qa_supp_data_
- _camdecmpswks.qa_cert_event_
- _camdecmpswks.test_extension_exemption_
- _camdecmpswks.emission_evaluation_
- _camdecmpswks.mats_bulk_file_

This is done so that the statuses can be set accordingly if the transaction fails. I don't think it would be beneficial to move these updates into another transaction.
