### ISSUE TITLE
Bug: QA Test Data Eval and Submission Status

### ISSUE THREAD

**Issue by ibarra-michelle** [US-EPA-CAMD/PI-1#6360]
Summary: As I was retesting [RETEST: Beta environment: Submissions are not processing](https://github.com/US-EPA-CAMD/easey-ui/issues/6250#top)#6250, in the test env, I successfully evaluated a QA Test Data file, however, the QA Test Data file Submission Status changed to "Updated on Host." The QA record was visible in the submission module, however, I was not able to select the QA test data record to Sign & Submit.  

**Steps to recreate the issue:**
1. Login to the test environment as a data submitter and select the following config: ORIS 404, Location 1.
2. Navigate to the MP module, export & import the MP data.
3. Navigate to the QA > Test Data module, click the import button, select Import from historical data, then select 2022 Q4, click the preview button.
4. Select the Test with the test number: 20224GFFM:112T1
5. In the QA Cert module UI, click the Test Type Group dropdown and select "Primary Element Inspection."
6. Click the Edit button for the record with the test #: 20224GFFM:112T1 to modify the Test Summary Data
7. Modify the Test Summary Data:
-  Modify the Test number to 20234GFFM:112T1
-  Modify the End Date to 03/02/2023
- Append the existing Test comment with the word "test."

8. Click the Save & Close button.
9. Navigate to the Emissions module, import 2023Q1 emission data from historical.
10. Before evaluating the QA and Emissions data, an admin must go into the System Admin module to allow the resubmission of test number 20234GFFM:112T1 and reopen the 2023Q1 Emissions submission window for the ORIS 404 Location1.
11. After the Admin tasks have been completed, the data submitter user should navigate to the Evaluation module, select the ORIS 404, Location 1, and 2023Q1 as the filter options, and click "Apply Filters."
13. After applying the filter, select the MP, QA Test Data, and Emissions records to evaluate.  
14. The evaluation status for each of the MP, QA, and Emissions records will result in the following (see the screenshot below):

**Different Evaluation Status**
1. MP: Permission to Resubmit Granted
16. QA: Updated to Host
17. Emissions: Resubmission Required 

![image](https://github.com/user-attachments/assets/c7b45a9f-9c6b-4efb-8fd2-5844896a3674)

**Comment by yonatan-dp** [comment]
@ibarra-michelle 
Clarification questions (don't have access to this facility in the Test env yet):

1. Is this happening only for this facility in the Test env?
2. Were you able to reproduce this error in another env? 
				
The fact of it not being selectable for submission on the UI is correct according to the data (and the UI logic).
Any selectable rows for submission must match the following two criteria

1. The evaluation status is 
"PASS", "INFO", or "ERR".
1. The submission availability code is 
"REQUIRE", "GRANTED", "CRITERR", or is missing/empty.
	
For the QA test data above, the submission availability code is UPDATED (Updated on Host) and therefore it is not selectable for submission. 

![image](https://github.com/user-attachments/assets/9b6fd6b7-3def-4574-85bd-9c826b1d79af)

I am continuing to look at why the submission availability code is set to UPDATED if you have not yet signed and submitted it. Let me know your thoughts on the two questions above.

**Comment by ibarra-michelle** [comment]
@yonatan-dp, please see my responses below, thx.
> 1. Is this happening only for this facility in the Test env?
I have only seen this problem on the reported facility in the test env.
> 2. Were you able to reproduce this error in another env?
I do not recall being able to reproduce this error in another env.

**Comment by yonatan-dp** [comment]
@ibarra-michelle, I looked at this defect in detail but I am not able to reproduce it in the test environment at all. I tried multiple times with ORIS 404, Location 1 and also with others. 

**For ORIS 404**

1. Before evaluating

![image](https://github.com/user-attachments/assets/63232be4-7dc6-42b3-a465-e759ca6d7573)

2. Evaluation Result. **As you can see, the QA line says `Resubmission Required` instead of `Updated to Host`**

![image](https://github.com/user-attachments/assets/403dc29f-fe56-4292-824e-7bf3de14c31e)

3. Before Submission. **Please note that it is selectable for submission**

![image](https://github.com/user-attachments/assets/8695d5d1-82cf-4db8-b428-3ad2893090fd)

**For ORIS 113, Location 1**

1. Before evaluating

![image](https://github.com/user-attachments/assets/9f19b6bb-56cd-47f6-b2a7-737c6ed3221d)

2. Before Submission. **Please note that it is selected for submission.  The QA line also says `Permission to Resubmit Granted` instead of `Updated to Host`**

![image](https://github.com/user-attachments/assets/e45652ba-9cd5-4b2f-9ba8-736d4ee93499)

**Manual Checks Performed**

I looked through the quartz-scheduler (which is where the evaluations are performed), camd-services, and also through our db scripts to locate anywhere the `submission_availability_cd` column of `camdecmpswks.qa_supp_data` is being set to `UPDATED` (which is where the data on the QA Line in the submission view is coming from).  I am not able to find such code. It is possible I may have missed something since this is a manual check. 

Currently, I do not have a theory as to how the QA line may have been set to 'UPDATED' **_in the evaluation stage_**.
