### ISSUE TITLE
Research: ECMPS 2.0 API Guidance Part 2

### ISSUE THREAD

**Issue by annalbrecht** [US-EPA-CAMD/PI-1#6495]
Finish providing complete details from Part 1 ticket & work with Yonatan to figure out the details.

**Comment by ergjustin** [comment]
@yonatan-dp 
1. The workspace APIs can only be accessed through the ECMPS-UI application and not via swagger due to CDX authentication flow integration. 

  Upon successful authentication in ECMPS-UI, a token is generated and stored in the browser's local storage. This token is then inserted into the API request headers under the `Authorization` key, where it is validated to verify the user's identity. 

       Authorization: Bearer <token>

2. To access the Workspace endpoint from ECMPS UI (client validation), which is available through the ECMPS application, follow these steps: Generate a client token using the client ID and client secret via the 'token/client' endpoint, store the token in local storage, and then include the client token in the API request headers under the `x-client-token` key for validation. 

         X-client-token: Bearer <token> 

-   All APIs from ECMPS-UI application will contain x-client-token 

-  All Workspace APIs from ECMPS-UI application will have two tokens 

    1.	User token /auth token: - Authorization
    2.	Client token: - x-client-token

 


**Note**: If planning to make one token Non-workspace API does not have Authorization headers.

When ECMPS offline feature `EASEY_AUTH_API_APP_STATUS` is in **TEST** mode, then the All APIs call only allow through ECMPS-UI application.

**Comment by yonatan-dp** [comment]
@ergjustin We should probably document somewhere that workspace APIs can still be accessed using other clients (such as Postman) since a user can still gain access to the client ID, client secrete, Auth token, and Client token (and other information) by inspecting the React code or by intercepting network traffic from ECMPS to the backend APIs.  The rest looks good to me.

**Comment by ergjustin** [comment]
@mark-hayward-erg @maheese 
Can you please review above comments.

**Comment by ergjustin** [comment]
Client token validation tickets :- #6489, #6490, #6491, #6492, #6493

**Comment by mark-hayward-erg** [comment]
Discussion was held on 12/16 to determine the purpose and feasibility of this change.  It was determined that using client id/token as a means to validate that calls to certain API endpoints come from ECMPS itself is not 100% possible or necessary.
