### ISSUE TITLE
Implement multi select for state

### ISSUE THREAD

**Issue by JorjaComer** [US-EPA-CAMD/PI-1#735]
## User Story 
As a user I want to enter filter criteria for multiple states so that I can see results for multiple states in one query
NO validation

## Acceptance Criteria 
Given that a user has entered multiple states 
When the API endpoint is executed
Then the system displays the results for multiple states (containing data elements below)

##  Data Elements 
Query results will include:
STATE | FACILITY_NAME | ORISPL_CODE | UNITID | OP_DATE | OP_HOUR | OP_TIME | GLOAD (MW) | SLOAD (1000lb/hr) | SO2_MASS (lbs) | SO2_MASS_MEASURE_FLG | SO2_RATE (lbs/mmBtu) | SO2_RATE_MEASURE_FLG | NOX_RATE (lbs/mmBtu) | NOX_RATE_MEASURE_FLG | NOX_MASS (lbs) | NOX_MASS_MEASURE_FLG | CO2_MASS (tons) | CO2_MASS_MEASURE_FLG | CO2_RATE (tons/mmBtu) | CO2_RATE_MEASURE_FLG | HEAT_INPUT (mmBtu) | PRIMARY_FUEL_INFO | SECONDARY_FUEL_INFO | UNIT_TYPE_INFO | SO2_CONTROL_INFO | PART_CONTROL_INFO | NOX_CONTROL_INFO | HG_CONTROL_INFO

## Testing
Test Case: [TC83](https://cvpcorp.testquality.com/project/11428/plan/19811/test/273591)
Tester: @davidkwartler

**Comment by sdhawan16** [comment]
Submitted PR for review:

Implemented multi select for State

- updated the paramsDTO so it can accept an array of strings for multiple state values
- updated repository query to search for all states is the provided list and also to convert all values in the list to uppercase
- added isStateCode decorator instead of the state validation pipe for consistency 
- commented out the isStateCode validation decorator for later use when implementing multi select validation
- updated unit tests to reflect multi select criteria 
- added APIQuery for state to controller with explode set to false
- commented out state validation pipe for potential future use

**Comment by david-cvp** [comment]
TC83 passed

https://easey-dev.app.cloud.gov/api/emissions-mgmt/apportioned/hourly/?page=1&perPage=3000&beginDate=2019-01-01&endDate=2019-01-31&state=TX,PA

![image.png](https://images.zenhubusercontent.com/5efcffd55c24786a6456ee1b/2433127e-e4b6-4a27-8bc3-272de9b636b0)
