### ISSUE TITLE
Enhance inactive filter display for configurations, locations, and methods

### ISSUE THREAD

**Issue by karenhwwoo** [US-EPA-CAMD/PI-1#832]
### Definition of Ready
- [x] Does this meet the INVEST criteria?
- [x] Does this have a clearly defined user?
- [x] Does this have an estimate?
- [x] Does this have acceptance criteria?
- [x] Does this have sufficient context (wireframes, business rules, etc.)?
- [x] Is this traceable to a feature, epic, or PI?

## User Story
As a user, I want to be able to view inactive Monitoring Plans, so that I can view all inactive MPs assigned to facility per [the wireframes](https://xd.adobe.com/view/c2462d8e-32fd-447b-a9c1-4067176bc335-9715/).

This user story is related to an edge case for #541.

## Acceptance Criteria
Given a user selects a facility with 
When only inactive configurations exist 
Then the system will display the retired locations and inactive monitoring methods by default
And the "Show Inactive" checkbox is checked and disabled

Please see SQL for Active/Inactive MP Logic: https://usepa.sharepoint.com/sites/CAMDCVPTeam/Shared%20Documents/TheEmissioners/ActiveInactive%20MP%20Logic.msg

The logic in in the following stored procedure in the ECMPS Client Database. 
•	ECMPS.[dbo].[UPDATE_MON_PLAN_CONFIGURATION]

## Testing
Tester: @mosesdeeCVP 
Test Case: [TC110](https://cvpcorp.testquality.com/project/11428/plan/19813/test/fullscreen/275972)

### Definition of Done
- [x] Have all Acceptance Criteria been agreed to and validated by the scrum team?
- [x] Has the code been unit tested and peer reviewed?
- [x] Have the functional tests been executed?
- [x] Have all defects been reviewed and dispositioned, resolved, or deferred?
- [x] Has the user story been accepted by the Product Owner?
- [x] Is the user story ready to be deployed to the staging/integration environment?

**Comment by mosesdeeCVP** [comment]
Enhancements: 

1. When in the Monitoring Plan once the user has selected the desired configuration and location, then clicks on the Show Inactive checkbox this causes the configurations and locations to reset to the default setting. The reset should not occur. Once the Show Inactive checkbox is clicked only the Inactive methods should appear in the table for the already selected configurations and locations.  Addressed in #874.

2. For configurations that have the same name, but one is active and the other is inactive, the system needs to be able to differentiate between the two and read them individually. As each are their own configuration, they just happen to share the name name.  Addressed in #874.

NOT DOING - 3. When in the Monitoring Plan and having selected the Show Inactive checkbox there will appear the inactive methods in the configurations drop down box. Some Facilities such as Berry (3), have both active and inactive configurations with the same name (4 and 5). 

4. When a configuration is clicked the system indicates which configuration is currently selected. When the inactive configuration with the same name as the active configuration is selected the system shows that the active configuration is selected instead of the chosen inactive configuration. Which ever configuration is selected should stay selected regardless of its name or if its active or inactive.  Addressed in #874.

4. The configuration and location drop down boxes reset when ever the user has multiple facilities open and is comparing between them. The selected configurations and locations should not reset or change unless the user does so themselves.  Addressed in #885.

5. When the user has checked the Show Inactive checkbox and also has multiple facilities open and is clicking between them the Show Inactive box gets unchecked every time you switch from one facility to another. The checked box should stay checked until the user unchecks it themselves.  Addressed in #885.

**Comment by JorjaComer** [comment]
Per 3.3 planning, decided we will change the system behavior to address data "weirdness". See comments above.

**Comment by mosesdeeCVP** [comment]
Test Case - Passed

**Comment by mosesdeeCVP** [comment]
![832 Enhance inactive filter display for configurations, locations, and methods.png](https://images.zenhubusercontent.com/5f807025564a417cbcdf6d69/567f4f65-3102-4351-820d-9c767f9f13d1)

**Comment by mosesdeeCVP** [comment]
Product Owner has approved the story – Ticket closed.
