### ISSUE TITLE
Update Hourly Emissions API Pagination and Order 

### ISSUE THREAD

**Issue by JorjaComer** [US-EPA-CAMD/PI-1#857]
As a user I want results to be paginated and ordered by date and hour so that the results are sorted 

Given a user has queried  the hourly emissions public API
When the API is executed
The the results are paginated 
And ordered by Facility > Unit > Date > Hour

Test Case: [TC99](https://cvpcorp.testquality.com/project/11428/plan/19811/test/275764)
Tester: @davidkwartler

**Comment by david-cvp** [comment]
Facility > Unit > Date > Hour

**Comment by junie-stigdon** [comment]
## Pull Request

- removed orderBy param from paginationDTO
  - orderBy logic now in repo
- moved pagination logic from service to repo (including response headers)
- renamed variable from "results" to "query" in repo
- updated unit tests

**Comment by david-cvp** [comment]
TC99 failed

Pagination works properly for low perPage numbers such as
https://easey-dev.app.cloud.gov/api/emissions-mgmt/apportioned/hourly?page=1&perPage=10&beginDate=2020-01-01&endDate=2020-01-31

Sort order meets acceptance criteria
![image.png](https://images.zenhubusercontent.com/5efcffd55c24786a6456ee1b/ae63c872-9c4e-451d-a3c6-1c1739ee34c6)

Created new bug #875 because TC99 fails for large perPage numbers

![image.png](https://images.zenhubusercontent.com/5efcffd55c24786a6456ee1b/f383fca3-38ac-4832-ba07-8eef33f1915c)

**Comment by david-cvp** [comment]
Bug #875 will be deferred. Closing out this ticket since basic functionality works properly.
