### ISSUE TITLE
Update Select Facility section drop downs to be 508 compliant

### ISSUE THREAD

**Issue by nalcvp** [US-EPA-CAMD/PI-1#899]
### Definition of Ready
- [ ] Does this meet the INVEST criteria?
- [ ] Does this have a clearly defined user?
- [ ] Does this have an estimate?
- [ ] Does this have acceptance criteria?
- [ ] Does this have sufficient context (wireframes, business rules, etc.)?
- [ ] Is this traceable to a feature, epic, or PI?

## User Story
As a user, I want to be able to select Facility section drop downs in a way so that they are 508 compliant.

## Acceptance Criteria
Given a user is in the system,
When a user is selecting Facility section drop downs,
Then they are compliant with 508 standards.

## Context
Correct, pagination in general will need care in keyboard accessibility and coding. See https://www.a11ymatters.com/pattern/pagination/ for an example. Right now one problem is that if a keyboard user activates a pagination page, 3 for example, visually the table is shifted, but when tabbing back, it goes to the last row of the table.
Other Notes

Be sure forms have programmatic names, right now they have visible labels but the labels are not coded with label tags and associated to the forms, see https://webaim.org/techniques/forms/controls
The dropdown with the active/inactive collapsible elements will be tricky, I'd suggest changing it to a checkbox outside that filters the dropdown values

## Testing
Test Case:
Tester:

### Definition of Done
- [ ] Have all Acceptance Criteria been agreed to and validated by the scrum team?
- [ ] Has the code been unit tested and peer reviewed?
- [x] Have the functional tests been executed?
- [x] Have all defects been reviewed and dispositioned, resolved, or deferred?
- [ ] Has the user story been accepted by the Product Owner?
- [ ] Is the user story ready to be deployed to the test/staging environments?

**Comment by aprematta** [comment]
Just took a look. In each case the visible label has a label tag, but it is lacking a for attribute that associates it to the id attribute of the select tag:
<label data-testid="label" class="usa-label">Configurations</label>

The select tag does have an aria label..... however this is not needed if the label mentioned above is properly coded with the for attribute. I would recommend adding the for attribute to the label tag and removing the aria label from the select tag, otherwise this may be flagged in a review.

<select data-testid="dropdown" class="usa-select" id="Configurationsundefined" name="Configurations" aria-label="Configurations dropdown" role="select"><option value="1, 2, CS0AAN" role="selectOption" selected="">1, 2, CS0AAN</option><option value="4" role="selectOption">4</option><option value="5" role="selectOption">5</option><option value="6A" role="selectOption">6A</option><option value="6B" role="selectOption">6B</option><option value="7A" role="selectOption">7A</option><option value="7B" role="selectOption">7B</option></select>

**Comment by aprematta** [comment]
Tested the facility dropdowns which are now 508 compliant
